Extend autopkgtest hints
canonical/ubuntu-maintainers-handbook pull request #12
Opened 2021-03-24 11:26 UTC by cpaelzer

I did intentionally not go deeper as that would then be for the man-ages or the linked wiki entries.
But to list them as options is IMHO helpful to new team members.

2021-03-24 20:07 UTC, bryceharrington requested changes
I like it, short and sweet.

I do suggest a few changes where a small bit more words may improve the reading from a new user POV.

Thanks for writing this up, you've at least taught me how to run autopkgtests in canonistack. :-D

2021-03-24 20:07 UTC, bryceharrington commented on PackageTests.md
> +[Finally to run the test on Canonistack](https://wiki.ubuntu.com/ProposedMigration#Reproducing_tests_in_the_cloud) is quite similar to the other invocations. Just replace the autopkgtest-runner with
The Canonistack web page docs don't mention `nova` or `setup-testbed`.  So might be helpful here to briefly state what the former means and what the latter does.

2021-03-25 06:37 UTC, cpaelzer commented on PackageTests.md
> +As usual with Canonistack you'd need to source your openstack RC file that sets region, auth and other environment variables.
> In case someone is new to Canonistack, 'As usual' might sound like it's glossing over a scary amount of technical unknowns. 

Which is exactly what I did :-)
 
> In going through the set up process for Canonistack, you'll have created an openstack RC file that sets region, auth and other environment variables. Go ahead and source this file, if you haven't already.

I still like your words more, adopted - thanks!

2021-03-25 06:37 UTC, cpaelzer commented on PackageTests.md
> +$ source novarc_bos01
Agreed, it helps to keep those in match

2021-03-25 06:49 UTC, cpaelzer commented on PackageTests.md
> +[Finally to run the test on Canonistack](https://wiki.ubuntu.com/ProposedMigration#Reproducing_tests_in_the_cloud) is quite similar to the other invocations. Just replace the autopkgtest-runner with
Indeed, added

2021-03-25 06:53 UTC, cpaelzer commented
The fixups for @bryce made me made me also improve a few other things here and there.
Thanks for the feedback, I've pushed my cleanups to this branch.
Is there anything else that would need to change or can we merge it this way now?

2021-03-25 13:15 UTC, utkarsh2102 requested changes
Great work, @cpaelzer. This looks great! 🎉 
I just have few minor comments below.

2021-03-25 13:15 UTC, utkarsh2102 commented on PackageTests.md
> +In going through the set up process for Canonistack, you'll have created an openstack RC file that sets region, auth and other environment variables. Go ahead and source this file, if you haven't alr
Maybe it's worth telling that you'll likely get it from the IS team, you just need to place and use the right one?
It's mentioned in the docs, I guess.

2021-03-25 13:15 UTC, utkarsh2102 commented on PackageTests.md
> +
This is bad formatting, unfortunately; see the output here: https://github.com/cpaelzer/ubuntu-maintainers-handbook/blob/extend-autopkgtest/PackageTests.md

These two lines should be placed inside backticks or/and you need to leave two spaces at the end of the first line so that MD renders it correctly.

2021-03-25 13:15 UTC, utkarsh2102 commented on PackageTests.md
> +with `nova` and adding the `setup-testbed` setup command.
If you intended to keep this in a separate line, you should leave another line. Otherwise, `with` -> `With`, at least.

2021-03-25 13:15 UTC, utkarsh2102 commented on PackageTests.md
> +  * Furthermore it selects the setup script `nova` from `/usr/share/autopkgtest/ssh-setup/nova` which happens to know how to deal with openstack
MD formatting issues against, unfortunately; see: https://github.com/cpaelzer/ubuntu-maintainers-handbook/blob/extend-autopkgtest/PackageTests.md

Instead of the 2nd point having 2 more points, it looks like there are 4 points in all, which doesn't seem right, right? :)

2021-03-25 13:15 UTC, utkarsh2102 commented on PackageTests.md
> +    --apt-pocket=proposed=src:srcpkg1,srcpkg2
Maybe worth adding an example like done for the above paragraph? But fine, either way.

2021-03-25 13:20 UTC, cpaelzer commented on PackageTests.md
> +In going through the set up process for Canonistack, you'll have created an openstack RC file that sets region, auth and other environment variables. Go ahead and source this file, if you haven't alr
It is mentioned in the linked Canonistack wiki - and since that touches internal processes and the handbook is public I wanted to leave it as I wrote.

2021-03-25 13:21 UTC, cpaelzer commented on PackageTests.md
> +with `nova` and adding the `setup-testbed` setup command.
Thanks, fixed
Now that we have the bullet list afterwards this line was no more necessary anyway

2021-03-25 13:34 UTC, cpaelzer commented on PackageTests.md
> +    --apt-pocket=proposed=src:srcpkg1,srcpkg2
Done and along that also added how to size a VM

2021-03-25 13:34 UTC, cpaelzer commented
Addressed the feedback of @bryceharrington and @utkarsh2102 now - anything else?

2021-03-25 14:51 UTC, cpaelzer commented
We have had two reviews (thanks!) and I've addressed all feedback.
I need to close out some of my concurrent tasks and would now merge this as-is.
If there are findings later it is easy enough to further improve the documentation.

2021-03-25 14:52 UTC, merged

2021-03-25 16:45 UTC, bryceharrington commented
On Wed, Mar 24, 2021 at 11:53:44PM -0700, Christian Ehrhardt wrote:
> The fixups for @bryce made me made me also improve a few other things here and there.
> Thanks for the feedback, I've pushed my cleanups to this branch.
> Is there anything else that would need to change or can we merge it this way now?

Just a couple markdown formatting things:

Looking at this page, the code snippets need to be set as pre-formatted
since the command lines starting at the `source` line are wrapping:

   https://github.com/cpaelzer/ubuntu-maintainers-handbook/blob/extend-autopkgtest/PackageTests.md

The two bullets under `ssh -s nova` need indented one more level.

2021-03-25 18:38 UTC, utkarsh2102 commented
I mentioned that in my review, maybe Christian missed it. But that's okay, no problem. I'll fix that, amongst other things.