Enhance patch review
canonical/ubuntu-maintainers-handbook pull request #149
Opened 2024-12-19 07:06 UTC by cpaelzer

As a follow up to realize we didn't catch the libvirt component mismatch I wanted to extend the review guidance.
And when touching it I found more and more that wasn't there yet so I kept (hopefully) improving it.

2024-12-20 01:55 UTC, bryceharrington requested changes
This brings some really good improvements to the patch review process, fixes some inaccuracies, and cleans things up.  I have several grammar suggestions to improve readability but these don't change meaning/policy too badly I hope.

I do have one bikeshed in challenging the symbols to use in the checklist, mainly to avoid any ambiguity.  I like the idea of relying on the template (esp. for new reviewees), and it makes sense to have a team-agreed consensus on the symbols.

2024-12-20 01:55 UTC, bryceharrington commented on MergeProposalReview.md
> +* If warranted for the case we provide further testing
Giving this a more active voice...

"In this review, we:
  * Review formal content for issues
  * Ensure adherence to team style guidelines
  * Identify common issues
  * Conduct further testing (when warranted)"

The first and third item are a bit ambiguously duplicative.

I do like how the original list spelled out tangible items to check (patch name & header, version numbers, changelog format).  However, the following text spells this out in more detail, so ok that this checklist just summarizes the process generally.

2024-12-20 01:55 UTC, bryceharrington commented on MergeProposalReview.md
> +reviewer to a particular aspect.
I think this can be simplified and just say:

"The following symbols indicate reviewer feedback on each aspect:"

2024-12-20 01:55 UTC, bryceharrington commented on MergeProposalReview.md
> +* `S` - Skipped by the reviewer as it seemed not mandatory or commensurate for this case. An example might be the component mismatch check which is helpful for a complex merge, but there is a tradeof
Honestly I think just "Skipped" is enough here.  There can be many reasons why one might skip a given item, and I don't think guidance is necessary.  Point is to encourage the reviewer to be transparent about what they didn't look at - for any reason.

2024-12-20 01:55 UTC, bryceharrington commented on MergeProposalReview.md
> +* Ensure the build in the PPA is ok on all architectures it is meant to build.
"* Verify that the PPA build is successful on all intended architectures."

2024-12-20 01:55 UTC, bryceharrington commented on MergeProposalReview.md
> +* If applicable relative to the changes made, consider if tests should be added, adapted or extended.
"* Where applicable, consider whether tests should be added, adapted, or extended to reflect the changes."

Or maybe a more direct phrasing:

"* Review the changes and determine if tests should be added, adapted, or extended."

2024-12-20 01:55 UTC, bryceharrington commented on MergeProposalReview.md
> +* Too many cases have been caught late and then intertwined in proposed-migration. Testing autopkgtest on the PPA helps to be confident before entering the archive.
"* Issues are too often discovered late, becoming entangled in proposed migrations. Testing with autopkgtest on the PPA helps ensure confidence before archive entry."

Or maybe:

"* Use autopkgtest on the PPA builds to ensure confidence before archive entry and avoid late discovery of issues that might lead to entanglement in other proposed migrations."

2024-12-20 01:55 UTC, bryceharrington commented on MergeProposalReview.md
> +* Especially for complex merges of packages in main, check if we accidentially or intentionally added new dependencies that would cause component mismatches, so we can adapt or prepare a [MIR](MainIn
"* For complex package merges in main that introduce new dependencies, check for potential component mismatches if those dependencies are only available in universe.  Such situations can lead to migration issues and may necessitate filing a MIR (Main Inclusion Request) for them."

2024-12-20 01:55 UTC, bryceharrington commented on MergeProposalReview.md
>    * If possible this should not be done by humans, but autopkgtests. And if it isn't consider adding them. But still sometimes there are situations where one wants to do a quick manual verification t
"* Manual installation of packages from the PPA may be performed to verify the builds, but this is optional.
    - Automated testing (autopkgtest) is preferred. Suggest adding DEP8 test cases where it would make sense.
    - In some situations, manual verification of certain behaviors may also be necessary for additional assurance."

2024-12-20 01:55 UTC, bryceharrington commented on MergeProposalReview.md
> +* `S` - Skipped by the reviewer as it seemed not mandatory or commensurate for this case. An example might be the component mismatch check which is helpful for a complex merge, but there is a tradeof
Also, I think this symbol legend is duplicative with the similar symbol legend down below, and I kind of think it's better to present it down there next to the template.  More comments on the symbols themselves down there.

2024-12-20 01:55 UTC, bryceharrington commented on MergeProposalReview.md
> +S = Skipped
'x' can be a bit ambiguous (to me this reads as "Incorrect", not "OK")  What do you think of this set?

```
+ = OK
! = Not OK - Reasons will be outlined in the lines below
? = Question  - Clarification will be requested in the lines below
N = Not Applicable 
S = Skipped
```

2024-12-20 07:19 UTC, cpaelzer commented on MergeProposalReview.md
> +to provide consistent good quality uploads. To do so we propose our changes
Absolutely - adopted your suggestion - thanks!

2024-12-20 07:20 UTC, cpaelzer commented on MergeProposalReview.md
> +as [merge proposals aganist `git-ubuntu` branches](MergeProposal.md).
thanks

2024-12-20 07:22 UTC, cpaelzer commented on MergeProposalReview.md
> +* If warranted for the case we provide further testing
Thank you, I've taken your words and very much like them.

And yes, we formerly spelled out tangible items but as you realized this led to spelling them out here AND in the mid section at the explanation. By now being "summary -> explanation -> template" we can avoid redundancy much better.

2024-12-20 07:31 UTC, cpaelzer commented on MergeProposalReview.md
> +* `S` - Skipped by the reviewer as it seemed not mandatory or commensurate for this case. An example might be the component mismatch check which is helpful for a complex merge, but there is a tradeof
I'm ok to not give the example on skipped - I get hat listing examples might limit people to think "only for that reason" and indeed all I wanted is transparency and allowing us to add more checks without making the process tedious with many things where they do not apply

I'll remove the "short symbols" here but give them short names.
Later in the template we can "symbol - short name", that should be well readable but at the same time keep symbols to where they belong (only once and in the template).

2024-12-20 07:32 UTC, cpaelzer commented on MergeProposalReview.md
> +reviewer to a particular aspect.
taken with slight modification to match the other improvements made

2024-12-20 07:33 UTC, cpaelzer commented on MergeProposalReview.md
> +* Ensure the build in the PPA is ok on all architectures it is meant to build.
WFM, sounds a bit smoother - adapted

2024-12-20 08:02 UTC, cpaelzer commented on MergeProposalReview.md
> +* If applicable relative to the changes made, consider if tests should be added, adapted or extended.
I like the former more, more than your second and more than what we had before.
Added

2024-12-20 08:03 UTC, cpaelzer commented on MergeProposalReview.md
> +* Too many cases have been caught late and then intertwined in proposed-migration. Testing autopkgtest on the PPA helps to be confident before entering the archive.
I like the second, thanks for giving me options :-)

2024-12-20 08:14 UTC, cpaelzer commented on MergeProposalReview.md
> +* Especially for complex merges of packages in main, check if we accidentially or intentionally added new dependencies that would cause component mismatches, so we can adapt or prepare a [MIR](MainIn
Hmm, it isn't that "only" complex cases can cause this - it is just easier to miss there.
Let me try to write something based on yours and mine ...

After a few rewrites it is more clear, only talks about what is needed and just avoids trying to also explain "when it is more or less likely needed". That is up to the reviewer to put in skipped or doing it.

2024-12-20 08:16 UTC, cpaelzer commented on MergeProposalReview.md
>    * If possible this should not be done by humans, but autopkgtests. And if it isn't consider adding them. But still sometimes there are situations where one wants to do a quick manual verification t
I like it, added

2024-12-20 08:17 UTC, cpaelzer commented on MergeProposalReview.md
> +S = Skipped
I wondered about it when adding and indeed I see the potential misdirection.
+ / ! are more generic indeed, I like it.

I also stripped the long text here as that is better in the explanation above.

2024-12-20 08:21 UTC, cpaelzer commented
@bryceharrington thanks for having a look, I think I was able to integrate all your suggestions directly or in minimally modified form. Ready for a re-review to merge or spot more.

2025-01-07 07:56 UTC, cpaelzer commented
@bryceharrington doing a review today I realized this didn't land yet, where you ok with the adaptations I made on your feedback or do you think more is needed?

2025-01-16 11:18 UTC, cpaelzer commented
I need to land this to avoid more reviews being done without these improvements,
happy to modify further as we identify issues with it.

2025-01-16 11:18 UTC, merged