Proposed migration
canonical/ubuntu-maintainers-handbook pull request #17
Opened 2021-07-07 02:58 UTC by bryceharrington

First cut at some initial docs about proposed migration.

The ubuntu wiki has a more authoritative guide, but is structured more as a reference.  This is intending to serve more as a tutorial and a collection point to links to the various sources of information a new +1 maintainer would need.

This still lacks a bit of polish (the glossary section in particular is going to render weirdly), but I think it's ready for an initial review.

2021-07-07 06:45 UTC, cpaelzer requested changes
Thanks for this writeup!
I've a few requests for changes/extension here and there, but I'm already +0.8 on this :-)
Have a look what you think about my suggestions and let me know once they are integrated (or explain my why they are not needed).

2021-07-07 06:45 UTC, cpaelzer commented on ProposedMigration.md
> +  2.  If (and only if) the fix is an SRU:
Or if we are in a freeze - should be added plus a link to https://wiki.ubuntu.com/FreezeExceptionProcess ?

2021-07-07 06:45 UTC, cpaelzer commented on ProposedMigration.md
> +      a.  Upload goes into an 'unapproved' queue
These (and the all the latter a/b/c indented lists) do not render correctly in all markdown readers.
It becomes one long convoluted line.
Making it "*" or "1./2./3." would fix that

2021-07-07 06:45 UTC, cpaelzer commented on ProposedMigration.md
> +  4.  Build binary package(s) from source package
To avoid misunderstanding maybe "launchpad will build" ?
As e.g. people from Debian are still used to build locally and upload binaries.

2021-07-07 06:45 UTC, cpaelzer commented on ProposedMigration.md
> +  5.  Run autopkgtests
Add a link to either of
https://packaging.ubuntu.com/html/auto-pkg-test.html
https://salsa.debian.org/ci-team/autopkgtest/blob/master/doc/README.package-tests.rst
https://autopkgtest.ubuntu.com/
here ?

2021-07-07 06:45 UTC, cpaelzer commented on ProposedMigration.md
> +      a.  SRU bug updated with request to verify
Add a link to https://wiki.ubuntu.com/StableReleaseUpdates#Verification ?

2021-07-07 06:45 UTC, cpaelzer commented on ProposedMigration.md
> +The first case covers all the usual normal build issues like syntax errors and so on.  In practice these are typically quite rare because developers tend to be very diligent at making sure their pack
Double space before "Fixes".
You correctly state that those are rare, maybe it is worth to mention that if they happen that is usually on less common platforms - and that one should consider using canonistack to reproduce it?

2021-07-07 06:45 UTC, cpaelzer commented on ProposedMigration.md
> +In the second case, local building was fine but the uploaded build may have failed on Launchpad due to a transitory issue such as a network outage, or a race condition, or other stressed resource.  O
double space before "Or"

2021-07-07 06:45 UTC, cpaelzer commented on ProposedMigration.md
> +For the third case, where a dependency is not the right version or is not present in the right pocket, the question becomes one of identifying what's wrong with the dependency and fixing it.  Be awar
double space before "Be".
Hmm - there are a lot of those - maybe they are intentional - in that case keep them.
If not then a simple search and replace will do it I guess.

2021-07-07 06:45 UTC, cpaelzer commented on ProposedMigration.md
> +Finally, there are also a miscellania of other problems that can result in build failures.  Many of these will be package-specific or situation-specific.  As you run into situations that crop up more
I think the common-enough-to-mention case here is the changed behavior or toolchain - very similar to your fourth case. Often caused by new glibc, gcc, python3, glib2.0 and such.

This kind essentially tends to happen when the release of the underlying libraries/toolchain is newer than the consuming project. Upstreams need time to adapt to changed behavior or function-prototypes. And in a similar fashion for the compiler toolchain that usually becomes more strict each release. And while one might say "but gcc vX was usable for 2 years; the time upstream projects really realize and care is when Distributions make it the default".
The important hint to add here is that quite often such an update causes the same kind of error in many places.
So if you find a package broken by gcc, glibc or similar update but can reproduce it to be fine with the older releases it is recommended to a) speak up in #ubuntu-devel as it is quite common to find other such cases and all need the same solution that might already exist b) report your findings in a way that others can re-use them if they run into equally affected FTFBS cases.
If upstreams do not respond in time it usually means to file a bug there (for long term resolution) and temporarily ignore the new warning via `-W...` or switch to the old behavior with `-f...`

2021-07-07 06:45 UTC, cpaelzer commented on ProposedMigration.md
> +If you are just coming up to speed on proposed migration duty, you'll likely be wondering "Where do I even start?!"  A good suggestion is to look for build failures towards the top of the page; build
OTOH it often means someone could have just uploaded (or watch this upload) this and already have an look at it. I'd recommend to at least pinging #ubuntu-devel and the uploader himself when picking from the top.

2021-07-07 06:45 UTC, cpaelzer commented on ProposedMigration.md
> +If you are just coming up to speed on proposed migration duty, you'll likely be wondering "Where do I even start?!"  A good suggestion is to look for build failures towards the top of the page; build
Another orthogonal but equally helpful hint I have for "where do I even start" is to ignore the top (too much churn and people look at it) and the bottom (often a lost cause) and instead look at the middle of the list - and there in particular at FTBFS on just one of the architectures. Those tend to be fine code that just didn't think of a particular behavior on other platforms. Those are usually easily reproducible and debuggable in canonistack. Once analyzed upstreams are often happy for the help as they are just not aware of some of those architectures.

2021-07-07 06:45 UTC, cpaelzer commented on ProposedMigration.md
> +If you file a bug report about a build or test failure shown on the update excuses page, tag the bug report 'update-excuse'.  This helps other developers see the investigation work you've already don
Using `update-excuse` instead of 'update-excuse' would help to be more aware of this special tag name.

2021-07-07 06:45 UTC, cpaelzer commented on ProposedMigration.md
> +* Has no binaries on any arch (- to x.y.z)
I've found that "Has no binaries on arch <foo>" are great candidates for debugging and resolving issues.
I've already mentioned this in detail at your section about "where to start" at processing update-excuses, but a short mention of this type here would be nice as well.

2021-07-07 06:45 UTC, cpaelzer commented on ProposedMigration.md
> +A common issue is that the test should be run against a version of a dependency present in the -proposed pocket, however it failed due to running against the version in -release.  Often this is strai
Add a link https://bazaar.launchpad.net/~ubuntu-archive/ubuntu-archive-tools/trunk/view/head:/retry-autopkgtest-regressions for retry-autopkgtest-regressions as well?

2021-07-07 07:43 UTC, utkarsh2102 requested changes
Awesome stuff, Bryce! 🎉 

Few concerns and suggestions inline. Besides, two more generic points:
- can you please remove the double spaces b/w the sentences?
- can you also wrap up lines in 80 words or so? Maybe you can skip this here for now, I'll format the entire handbook to do that for easy readability, I believe. Up to you.

Thank you for working on this!

2021-07-07 07:43 UTC, utkarsh2102 commented on ProposedMigration.md
> +The build step can hit failures for several general classes of problems.  First are regular build problems that can be easily reproduced locally (and that should have been addressed before uploading)
I'd also mention the architecture-specific problems. For example, ruby2.7 built on all arches except for arm*. So things like that.

2021-07-07 07:43 UTC, utkarsh2102 commented on ProposedMigration.md
> +In the second case, local building was fine but the uploaded build may have failed on Launchpad due to a transitory issue such as a network outage, or a race condition, or other stressed resource.  O
Worth adding that you can't click on "retry" and need a core-dev's assistance, heh.

2021-07-07 07:43 UTC, utkarsh2102 commented on ProposedMigration.md
> +For the third case, where a dependency is not the right version or is not present in the right pocket, the question becomes one of identifying what's wrong with the dependency and fixing it.  Be awar
+1. I'd rather have them removed, not consistent with other pages, or are they?

2021-07-07 07:43 UTC, utkarsh2102 commented on ProposedMigration.md
> +The fourth case of ABI changes comes up particularly when Ubuntu is introducing new versions of language runtime environments or core libraries; i.e. new glibc, ruby, python3, phpunit, et al.  Your p
aw, you didn't mention PHP itself? 😞 
(lol, I am just kidding!)

2021-07-07 07:43 UTC, utkarsh2102 commented on ProposedMigration.md
> +
I also would like to mention that even when there seems no apparent reason for a package to migrate in the update_excuses page, the answer might lie in the update_output page, which talks about the uninstallability issues. Having gone through this very recently (and multiple times) and having all the documentation at hand, I think I can write a patch after this one has been merged. Thoughts?

2021-07-07 07:43 UTC, utkarsh2102 commented on ProposedMigration.md
> +A common issue is that the test should be run against a version of a dependency present in the -proposed pocket, however it failed due to running against the version in -release.  Often this is strai
Also worth mentioning again that a non-core-dev cannot retry anything whatsoever. They'd need assistance of a core-dev.

2021-07-07 07:43 UTC, utkarsh2102 commented on ProposedMigration.md
> +Autopkgtest runs tests in a controlled network environment, so if a test case expects to download material from the internet, it will likely fail.  If the test case is attempting to download a depend
Trivial but also worth adding that a bunch of tests fail because of `HTTP_PROXY` issues. I don't know if it's a good fit for here but it has bitten me a lot many times :sigh:

2021-07-07 07:43 UTC, utkarsh2102 commented on ProposedMigration.md
> +If an autopkgtest is badly written, it may be too challenging to get it to pass.  In these extreme cases, its possib\
I am afraid that `possib\` isn't the right syntax. Please make it "possible" again and shift to the next line, markdown will automatically understand what you wanted to do.

2021-07-07 07:43 UTC, utkarsh2102 commented on ProposedMigration.md
> +File a MP against it with a description indicating the lp bug#, rationale for why the test can and should be skipped\
Redundant "\" at the end, please remove this? 😅

2021-07-07 07:43 UTC, utkarsh2102 commented on ProposedMigration.md
> +Reviewers should be 'canonical-server', 'ubuntu-release', and any archive admins or foundations team members you've \
Redundant "\" at the end, please remove this? 😅

2021-07-07 07:43 UTC, utkarsh2102 commented on ProposedMigration.md
> +Checkout [https://git.launchpad.net/~ubuntu-release/britney/+git/hints-ubuntu](lp:~ubuntu-release/britney/hints-ubuntu)
Missing fullstop in the end? :P

2021-07-07 10:01 UTC, basak commented on ProposedMigration.md
> +If you file a bug report about a build or test failure shown on the update excuses page, tag the bug report 'update-excuse'.  This helps other developers see the investigation work you've already don
It might be worth pointing out that doing this results in the bug appearing in the relevant place on the excuses page.

2021-07-07 18:39 UTC, bryceharrington commented
Thanks for the feedback Christian!  Esp. all the hyperlinks, which will
help make this doc a good jump off point to all the various information
sites.

On Tue, Jul 06, 2021 at 11:46:01PM -0700, Christian Ehrhardt wrote:
> @cpaelzer requested changes on this pull request.
> 
> Thanks for this writeup!
> I've a few requests for changes/extension here and there, but I'm already +0.8 on this :-)
> Have a look what you think about my suggestions and let me know once they are integrated (or explain my why they are not needed).
> 
> >  
> -Non-sru:
> +  0.  Issue identified, fixed, and packaged
> +  1.  *source.changes uploaded
> +  2.  If (and only if) the fix is an SRU:
> 
> Or if we are in a freeze - should be added plus a link to https://wiki.ubuntu.com/FreezeExceptionProcess ?

Incorporated

> >  
> -Non-sru:
> +  0.  Issue identified, fixed, and packaged
> +  1.  *source.changes uploaded
> +  2.  If (and only if) the fix is an SRU:
> +      a.  Upload goes into an 'unapproved' queue
> 
> These (and the all the latter a/b/c indented lists) do not render correctly in all markdown readers.
> It becomes one long convoluted line.
> Making it "*" or "1./2./3." would fix that

That's too bad.  Guess I'll change the sub-level to *'s.

> -Non-sru:
> +  0.  Issue identified, fixed, and packaged
> +  1.  *source.changes uploaded
> +  2.  If (and only if) the fix is an SRU:
> +      a.  Upload goes into an 'unapproved' queue
> +      b.  SRU team reviews and approves... (goto 3)
> +      c.  ...or disapproves (goto 0)
> +  3.  Upload goes into [codename]-proposed queue
> +  4.  Build binary package(s) from source package
> 
> To avoid misunderstanding maybe "launchpad will build" ?
> As e.g. people from Debian are still used to build locally and upload binaries.

Incorporated

> -Non-sru:
> +  0.  Issue identified, fixed, and packaged
> +  1.  *source.changes uploaded
> +  2.  If (and only if) the fix is an SRU:
> +      a.  Upload goes into an 'unapproved' queue
> +      b.  SRU team reviews and approves... (goto 3)
> +      c.  ...or disapproves (goto 0)
> +  3.  Upload goes into [codename]-proposed queue
> +  4.  Build binary package(s) from source package
> +  5.  Run autopkgtests
> 
> Add a link to either of
> https://packaging.ubuntu.com/html/auto-pkg-test.html
> https://salsa.debian.org/ci-team/autopkgtest/blob/master/doc/README.package-tests.rst
> https://autopkgtest.ubuntu.com/
> here ?

I'll add all three links, but at this particular spot in the doc the
first link feels most appropriate.  I'll work the other two in below.

> -Non-sru:
> +  0.  Issue identified, fixed, and packaged
> +  1.  *source.changes uploaded
> +  2.  If (and only if) the fix is an SRU:
> +      a.  Upload goes into an 'unapproved' queue
> +      b.  SRU team reviews and approves... (goto 3)
> +      c.  ...or disapproves (goto 0)
> +  3.  Upload goes into [codename]-proposed queue
> +  4.  Build binary package(s) from source package
> +  5.  Run autopkgtests
> +  6.  Verify other archive consistency checks
> +      a.  Are binary packages installable?
> +      b.  Are all required dependencies at the right version?
> +  7.  If (and only if) the fix is an SRU:
> +      a.  SRU bug updated with request to verify
> 
> Add a link to https://wiki.ubuntu.com/StableReleaseUpdates#Verification ?

Incorporated

> -When tests succeeded, built fine:
> -- In disco, it would migrate from proposed to release
> -- special cases: not installable, waiting on dependency
> -3 things needed:
> --- not installable: depends on something not existing, for example
> --- dependency: Dependent package has not gone into release yet.
> --- all pkg tests are OK
> +The build step can hit failures for several general classes of problems.  First are regular build problems that can be easily reproduced locally (and that should have been addressed before uploading).  Second are intermittent platform problems, where simply retrying the build once or twice can result in a successful build.  Third are dependency problems, where the task is to get some other package to be the right version in the release pocket so that the build will succeed.  Fourth are ABI changes with dependencies; these often just need a no-change rebuild.  And last are all the other myriad package-specific build problems, that typically require some particular tweak to the package itself.
> +
> +The first case covers all the usual normal build issues like syntax errors and so on.  In practice these are typically quite rare because developers tend to be very diligent at making sure their packages build before uploading.  Fixes for these is the usual standard development work.
> 
> Double space before "Fixes".

I've always been a doublespace-between-sentences guy and probably always
will.  But I believe Markdown automatically translates them into
appropriate spacing during formatting, so probably not a worry.

> You correctly state that those are rare, maybe it is worth to mention that if they happen that is usually on less common platforms - and that one should consider using canonistack to reproduce it?

Sure, incorporated:

"The second case is similar to the first but pertains to issues that arise only on specific platforms.  Common situations are tests or code that relies on [https://en.wikipedia.org/wiki/Endianness](endianness) of data types and so breaks on big-endian systems (e.g. s390x), code expecting 64-bit data types that breaks on 32-bit (e.g. armhf), and so on.  [https://wiki.canonical.com/InformationInfrastructure/IS/CanoniStack-BOS01](Canonistack provides hardware) that Canonical employees can use to attempt reproduction of these problems.  Take note with i386 particularly in that it often fails less due to data type issues but more because it is a partial port and has numerous limitations that require special handling, as described on the [https://wiki.ubuntu.com/i386](i386 troubleshooting page)."

I'm not sure about linking to intranet docs from a doc that will be
externally visible, but it seems not worth mentioning Canonistack
without the corresponding landing page for how to use it.

I also took this opportunity to tack on some info about i386 and how
its platform issues are bit different than just architectural, with a
link to the right page for those issues.  i386 might be worth a full
paragraph itself, but maybe just this sentence is enough.

> +For the third case, where a dependency is not the right version or is not present in the right pocket, the question becomes one of identifying what's wrong with the dependency and fixing it.  Be aware there may be some situations where the problem really is with the dependency itself, and the solution is to change the version of the dependency, or adjust the dependency version requirement, or so forth.  These latter solutions often require asking for an archive admin's help on the #ubuntu-release IRC channel.
> 
> double space before "Be".
> Hmm - there are a lot of those - maybe they are intentional - in that case keep them.
> If not then a simple search and replace will do it I guess.

They're intentional, but if someone cleaned them up later it wouldn't
bother me.  It's too much muscle memory for me now.

> +Finally, there are also a miscellania of other problems that can result in build failures.  Many of these will be package-specific or situation-specific.  As you run into situations that crop up more than a couple times please update these docs.
> 
> I think the common-enough-to-mention case here is the changed behavior
> or toolchain - very similar to your fourth case. Often caused by new
> glibc, gcc, python3, glib2.0 and such.

This is what I intend the fifth case to be, so will fold your notes into
that one.  From a +1 maintenance POV a toolchain/api change is a much
more sigificant problem than just an incorrect dependency version.  Both
are quite common problems, but need distinct workflows to address them.

> This kind essentially tends to happen when the release of t [...]

2021-07-07 19:41 UTC, bryceharrington commented
On Wed, Jul 07, 2021 at 12:43:21AM -0700, Utkarsh Gupta wrote:
> @utkarsh2102 requested changes on this pull request.
> 
> Awesome stuff, Bryce! 🎉 
> 
> Few concerns and suggestions inline. Besides, two more generic points:
> - can you please remove the double spaces b/w the sentences?
> - can you also wrap up lines in 80 words or so? Maybe you can skip this here for now, I'll format the entire handbook to do that for easy readability, I believe. Up to you.
> 

Heh, I'll leave that formatting to you.

I wasn't sure if markdown would properly format line-wrapped text and
have been too lazy to test it.  If it works, then I'd definitely +1 that
change.

> +Often the migration proceeds automatically, but when there are issues our involvement is needed to sort things out.  Sometimes the package having the problem is one we've uploaded ourselves, so naturally want to work on solving the issue.  But in other times the issue arises organically such as via something that auto-sync'd from Debian, or a side-effect from some other change in the distro, and thus have no defined "owner".  For these latter problems (and for the former when they've become tricky), the Ubuntu project requires distro developers to devote a portion of their time to focusing on migration issues generally, on a rotating basis each working a few days or week at a time.
> 
> Maybe add "called +1" or something similar at last?

I didn't want to have to get into why it's called "+1 maintenance" so
intentionally just kept to a generic term for it.

> Also, aren't these just for Canonical employees and not Ubuntu devs in general?

This document is geared to Canonical employees so yeah that's going to
be 90% of the audience, however the document is public so does provide
reference for the community generally (IOW there's no reason a community
person *couldn't* use this information).

Also, while +1 maintainers would be the primary consumer of this
information, the intent is to also provide a reference for folks working
on transitions or just trying to figure out WTF their fix is stuck in
-proposed.

> +Failure to Build From Source (FTBFS)
> +------------------------------------
> +
> +The build step can hit failures for several general classes of problems.  First are regular build problems that can be easily reproduced locally (and that should have been addressed before uploading).  Second are intermittent platform problems, where simply retrying the build once or twice can result in a successful build.  Third are dependency problems, where the task is to get some other package to be the right version in the release pocket so that the build will succeed.  Fourth are ABI changes with dependencies; these often just need a no-change rebuild.  And last are all the other myriad package-specific build problems, that typically require some particular tweak to the package itself.
> 
> I'd also mention the architecture-specific problems. For example, ruby2.7 built on all arches except for arm*. So things like that.

Incorporated

> +The fourth case of ABI changes comes up particularly when Ubuntu is introducing new versions of language runtime environments or core libraries; i.e. new glibc, ruby, python3, phpunit, et al.  Your package may fail to build because one of its dependencies was built against a different version of glibc or whatever, and needs (no-change) rebuilt (and/or patched) to build with the new version.
> 
> aw, you didn't mention PHP itself? 😞 
> (lol, I am just kidding!)

Hah I can't always resist but did this time.  :-)

> +Finally, there are also a miscellania of other problems that can result in build failures.  Many of these will be package-specific or situation-specific.  As you run into situations that crop up more than a couple times please update these docs.
> +
> 
> I also would like to mention that even when there seems no apparent reason for a package to migrate in the update_excuses page, the answer might lie in the update_output page, which talks about the uninstallability issues. Having gone through this very recently (and multiple times) and having all the documentation at hand, I think I can write a patch after this one has been merged. Thoughts? 

Yes, thanks that would be great.

I opted to ignore it since the use cases needing it are (IMHO) rare, but
you're right that they do come up time to time.  The existing docs
(https://wiki.ubuntu.com/ProposedMigration#The_update_output.txt_file_is_completely_unreadable.21)
are not very thorough, unfortunately.  Perhaps a good angle would be to
explain the specific use cases in paint-by-number fashion so you don't
have to document how to actually decode update_output.txt.


> +### Other Common Issues ###
> +
> +Autopkgtest runs tests in a controlled network environment, so if a test case expects to download material from the internet, it will likely fail.  If the test case is attempting to download a dependency (e.g. via PIP or Maven), sometimes this can be worked around by adding the missing dependency to ```debian/tests/control```.  If it is attempting to download an example file, then it may be possible to make the test case use a local file, or to load from the proxy network.
> 
> Trivial but also worth adding that a bunch of tests fail because of `HTTP_PROXY` issues. I don't know if it's a good fit for here but it has bitten me a lot many times :sigh:

Agreed they do come up now and then, and are perfect types of items to
document here.  I alluded to proxy issues vaguely, but perhaps you could
elaborate with some tangible advice (and/or examples) for dealing with
it?  If there's enough to say on it, may be worth calling out with its
own header above this one.

> +Skipping tests
> +--------------
> +
> +If an autopkgtest is badly written, it may be too challenging to get it to pass.  In these extreme cases, its possib\
> 
> I am afraid that `possib\` isn't the right syntax. Please make it "possible" again and shift to the next line, markdown will automatically understand what you wanted to do.
> 

Ah thanks, yes the stray line breaks must have come from some cut and
pasting in emacs.

> +Skipping tests
> +--------------
> +
> +If an autopkgtest is badly written, it may be too challenging to get it to pass.  In these extreme cases, its possib\
> +le to request that test failures be ignored for purposes of package migration.
> +
> +Checkout [https://git.launchpad.net/~ubuntu-release/britney/+git/hints-ubuntu](lp:~ubuntu-release/britney/hints-ubuntu)
> 
> Missing fullstop in the end? :P

I'll rewrite this section.  This text is verbatim from Karl's
misc. notes, but should be revised to discuss hinting more generally.
I'll do that as a new commit in this thread.

> -Non-sru:
> +  0.  Issue identified, fixed, and packaged
> +  1.  *source.changes uploaded
> +  2.  If (and only if) the fix is an SRU:
> +      a.  Upload goes into an 'unapproved' queue
> +      b.  SRU team reviews and approves... (goto 3)
> +      c.  ...or disapproves (goto 0)
> +  3.  Upload goes into [codename]-proposed queue
> +  4.  Build binary package(s) from source package
> +  5.  Run autopkgtests
> 
> Yeah, besides the autopkgtests of the package itself, the autopkgtests of its reverse{-build}-dependencies are run, too.
> 

Incorporated

> +In the second case, local building was fine but the uploaded build may have failed on Launchpad due to a transitory issue such as a network outage, or a race condition, or other stressed resource.  Or it might have failed due to a strange dependence on some variable like the day of the week.  In these cases, clicking on the "Retry Build" button in Launchpad once or twice can sometimes cause the build to randomly succeed, thus allowing the transition to proceed.  Needless to say, we don't wish for such unpredictabilities in the build process, so if the problem reoccurs and if you can narrow down the cause, it can be worthwhile to find the root cause and figure out how to fix it properly.
> 
> Worth adding that you c [...]

2021-07-07 19:45 UTC, bryceharrington commented
On Wed, Jul 07, 2021 at 03:01:16AM -0700, basak wrote:
> @basak commented on this pull request.
> 
> 
> 
> > @@ -41,6 +41,12 @@ Many of the items on the page are not actually broken, they're just blocked by s
>  If you are just coming up to speed on proposed migration duty, you'll likely be wondering "Where do I even start?!"  A good suggestion is to look for build failures towards the top of the page; build failures tend to be more localized and more deterministic as to cause, and items towards the top of the page will have had fewer eyeballs on them since they're newer, and so have a higher chance of being something simple.
>  
>  
> +Bug Reports for Migration Problems
> +----------------------------------
> +
> +If you file a bug report about a build or test failure shown on the update excuses page, tag the bug report 'update-excuse'.  This helps other developers see the investigation work you've already done, and can be used to identify the next-action.  Mark yourself as the Assignee if you're actively working on the issue, and leave the bug unsubscribed if you aren't so that others can carry things forward.
> 
> It might be worth pointing out that doing this results in the bug appearing in the relevant place on the excuses page.
> 

Ah thanks, yes forgot that important detail.

Bryce

2021-07-07 19:56 UTC, basak commented
On Wed, Jul 07, 2021 at 12:41:38PM -0700, Bryce Harrington wrote:
> > Also, aren't these just for Canonical employees and not Ubuntu devs in general?
> 
> This document is geared to Canonical employees so yeah that's going to
> be 90% of the audience, however the document is public so does provide
> reference for the community generally (IOW there's no reason a community
> person *couldn't* use this information).
> 
> Also, while +1 maintainers would be the primary consumer of this
> information, the intent is to also provide a reference for folks working
> on transitions or just trying to figure out WTF their fix is stuck in
> -proposed.

It's still misleading to say "the Ubuntu project requires distro
developers" though. That's objectively not true. Even if this is only
read by Canonical employees, this might lead to new Canonical employees
leaning on non-Canonical Ubuntu developers to do work that they wrongly
think they are required to do.

How about "Canonical requires some of its distro developer employees"
instead?

2021-07-07 20:08 UTC, bryceharrington commented
On Wed, Jul 07, 2021 at 12:56:22PM -0700, basak wrote:
> On Wed, Jul 07, 2021 at 12:41:38PM -0700, Bryce Harrington wrote:
> > > Also, aren't these just for Canonical employees and not Ubuntu devs in general?
> > 
> > This document is geared to Canonical employees so yeah that's going to
> > be 90% of the audience, however the document is public so does provide
> > reference for the community generally (IOW there's no reason a community
> > person *couldn't* use this information).
> > 
> > Also, while +1 maintainers would be the primary consumer of this
> > information, the intent is to also provide a reference for folks working
> > on transitions or just trying to figure out WTF their fix is stuck in
> > -proposed.
> 
> It's still misleading to say "the Ubuntu project requires distro
> developers" though. That's objectively not true. Even if this is only
> read by Canonical employees, this might lead to new Canonical employees
> leaning on non-Canonical Ubuntu developers to do work that they wrongly
> think they are required to do.
> 
> How about "Canonical requires some of its distro developer employees"
> instead?

Sure, incorporated, thanks.

Bryce

2021-07-08 06:43 UTC, cpaelzer commented
The email replies work fine as a conversation, but we had plenty of open review threads up here.
I've checked and you have indeed addressed them all - thanks!
To me it looks good now, not sure if you want a review of the new revised content before merging? IIRC @sergiodj wanted to have a look as well - now might be a good time.

2021-07-08 14:59 UTC, bryceharrington commented
On Wed, Jul 07, 2021 at 11:43:29PM -0700, Christian Ehrhardt wrote:
> The email replies work fine as a conversation, but we had plenty of open review threads up here.
> I've checked and you have indeed addressed them all - thanks!
> To me it looks good now, not sure if you want a review of the new revised content before merging? IIRC @sergiodj wanted to have a look as well - now might be a good time.

I think it's good to land now.  Sergio is a bit tied up with stuff so
sounds like he wouldn't be able to get to it soon.  I'm sure we'll have
refinements in the future so he can follow up with his own ideas when
he's ready.

I will need your help landing it though, as I don't think I've got the
permissions to do so in our gitlab.

Bryce

2021-07-08 15:45 UTC, utkarsh2102 commented
Alrighty, here we go..

2021-07-08 15:45 UTC, merged

2021-07-08 16:28 UTC, bryceharrington commented
Thanks!

On Thu, Jul 08, 2021 at 08:45:50AM -0700, Utkarsh Gupta wrote:
> Merged #17 into master.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/canonical/ubuntu-maintainers-handbook/pull/17#event-4995806352