New entry on Package Merging: Syncs
canonical/ubuntu-maintainers-handbook pull request #28
Opened 2021-08-17 13:21 UTC by mirespace

Hi team,

as a result of the freeipmi merge that resulted in a sync task, I wrote a little about that. Christian gave me several pages about Syncs in the Ubuntu wiki that I tried to summarize, but I focused on the case that we're doing a merge task and we discovered we have not Ubuntu delta, so I don't enter in detail about the other cases because I don't face them yet (but I did this like a new page for this reason, in the sense we wanted to do it in the future).

I would have liked to talk a little more about the message "Source package <whatever> is temporarily blacklisted (blacklisted_current).", to see how to track these special cases ... so suggestions are more than welcome.

Anything you consider needs a change, feel free to let me know about it (suggestions also, of course!).

Thanks in advance!

2021-08-17 13:55 UTC, cpaelzer requested changes

2021-08-17 13:55 UTC, cpaelzer commented on Syncs.md
> +we suddenly realise that there are no Ubuntu changes because Debian or upstream has incorporated
s/we suddenly/we might suddenly/

s/Ubuntu changes/Ubuntu changes left/

2021-08-17 13:55 UTC, cpaelzer commented on PackageMerging.md
> +If all the commits are empty, or you realized there aren't logical changes, you're facing a **Sync Request**, not a merge anymore. Check [this](Syncs.md) to continue.
I actually like the breakout into an extra page even though I thought otherwise before.
Over time we might identify a few more spots where we can mention it and add links to the page.

2021-08-17 13:55 UTC, cpaelzer commented on Syncs.md
> +them (the logical change has became redundant). Sometimes we recognise this because an
s/the logical change has became/all logical changes have become/

2021-08-17 13:55 UTC, cpaelzer commented on Syncs.md
> +them (the logical change has became redundant). Sometimes we recognise this because an
s/because an/everything becomes an/

2021-08-17 13:55 UTC, cpaelzer commented on Syncs.md
> +That is, while we are looking for the logical changes
This paragraph says nothing else than the one above - can be removed to avoid duplication.

if you insist on keeping it is more like "if all that remains is ..." and then:
s/no description of maintainer/update-maintainers/
s/version change/changelog stanzas/

2021-08-17 13:55 UTC, cpaelzer commented on Syncs.md
> +Why is better a sync?
Why is better a sync? -> Why a sync is better?

2021-08-17 13:55 UTC, cpaelzer commented on Syncs.md
> +In Ubuntu, we have an automated mechanism that synchronizes new releases of a Debian package to
s/releases/versions/

2021-08-17 13:55 UTC, cpaelzer commented on Syncs.md
> +packages that are as-is in our Ubuntu series (without Ubuntu or upstream modifications and built directly  from Debian source packages in Ubuntu's autobuilders). So, if we find a package that can be
remove "packages that are as-is in"

2021-08-17 13:55 UTC, cpaelzer commented on Syncs.md
> +packages that are as-is in our Ubuntu series (without Ubuntu or upstream modifications and built directly  from Debian source packages in Ubuntu's autobuilders). So, if we find a package that can be
double whitespace at "directly  from"

2021-08-17 13:55 UTC, cpaelzer commented on Syncs.md
> +packages that are as-is in our Ubuntu series (without Ubuntu or upstream modifications and built directly  from Debian source packages in Ubuntu's autobuilders). So, if we find a package that can be
autobuilders is not the usual term and not needed here.
Also there can't be an "upstream modifications" - I think we should stay to the usual terms which makes the in-bracket content overall:
"(without Ubuntu or upstream modifications and built directly  from Debian source packages in Ubuntu's autobuilders)"
->
"(without Ubuntu delta on top of Debian source package)"

2021-08-17 13:55 UTC, cpaelzer commented on Syncs.md
> +packages that are as-is in our Ubuntu series (without Ubuntu or upstream modifications and built directly  from Debian source packages in Ubuntu's autobuilders). So, if we find a package that can be
"So," is usually from verbal speech, not for a document - remove it please.

2021-08-17 13:55 UTC, cpaelzer commented on Syncs.md
> +packages that are as-is in our Ubuntu series (without Ubuntu or upstream modifications and built directly  from Debian source packages in Ubuntu's autobuilders). So, if we find a package that can be
s/package that can/package can/
s/be re-synchronized/become a sync/
s/better to ask/it is better to ask/
s/that to deal/than to deal/

2021-08-17 13:55 UTC, cpaelzer commented on Syncs.md
> +Tha automated process has a window slot into the whole Ubuntu release cycle: [the Debian Import Freeze](https://wiki.ubuntu.com/DebianImportFreeze).
s/Tha/The/
s/automated process syncing packages from Debian automatically/
s/has a window slot into the whole /is active for only some of the/

2021-08-17 13:55 UTC, cpaelzer commented on Syncs.md
> +- Upload the build log (from sbuild or pbuilder) of the Debian package compiled in the Ubuntu release as proof that the new Debian version still compiles in Ubuntu: you cannot upload the complete bui
That is wrong'ish
While you can, you'd not use sbuild/pbuilder.

Instead you'd run `dch -i` which will take the Debian changelog and add a new ...ubuntu1
In that changelog you'd just say "build debian version to verify before a sync" or anything like that.
That PPA you'd attach to the MP as you'd do for a merge.

2021-08-17 13:55 UTC, cpaelzer commented on Syncs.md
> +For other sync situations, you can review [this](https://wiki.ubuntu.com/SyncRequestProcess). The more common case is to request for an explicit sync via [filling a Launchpad Bug](https://wiki.ubuntu
s/The more common case/Outside of the server team process the common way/

2021-08-17 13:55 UTC, cpaelzer commented on Syncs.md
> +How the sync itself is performed?
=> How to perform a sync

2021-08-17 13:55 UTC, cpaelzer commented on Syncs.md
> +If you have the permissions to upload the package to Ubuntu, you will do it using the [**syncpackage** tool](http://manpages.ubuntu.com/manpages/impish/man1/syncpackage.1.html) as stated [here](https
s/will do it/can issue a sync request/

2021-08-17 13:55 UTC, cpaelzer commented on Syncs.md
> +You can check the status of the build as another usual upload:
s/can/should/
s/another usual/on any other/

2021-08-17 13:55 UTC, cpaelzer commented on Syncs.md
> +- In the packages overview page: You can check the satus of a concrete architecture build and its buildlog - i.e. the freeipmi amd64 [buildlog](https://launchpad.net/ubuntu/+source/freeipmi/1.6.6-4/+
s/satus/status/
s/a concrete architecture build/an upload, its builds/

The overview page needs a link, the only links you have so far are for the log and the publication history.
So I guess you want to throw in https://launchpad.net/ubuntu/+source/freeipmi

Also I know these are from example and it is good to have real links, but maybe the doc should show the pattern.
Like `https://launchpad.net/ubuntu/+source/<src package name>/+publishinghistory`

2021-08-17 13:55 UTC, cpaelzer commented on Syncs.md
> +A list of packages that maybe can be considered for syncing in the ondevelopment series (impish at the moment of writting) can be found [here](https://launchpad.net/ubuntu/impish/+localpackagediffs).
s/ondevelopment/development/

2021-08-17 13:55 UTC, cpaelzer commented on Syncs.md
> +A list of packages that maybe can be considered for syncing in the ondevelopment series (impish at the moment of writting) can be found [here](https://launchpad.net/ubuntu/impish/+localpackagediffs).
What does the last sentence try to tell me?
Are you hinting at the "package merge opportunity" mails of bryce?

In fact this last section does NOT hint at "considered for syncs" it is pointing to lists for potential merges of which some happen to end up being syncs. And so is bryce mail.
TBH - for clarify of the page I'd suggest to remove the while "Other info" section.

2021-08-17 13:55 UTC, cpaelzer commented on Syncs.md
> +You can read more about syncing from a parent series on Launchpad [here](https://launchpad.net/+help-soyuz/derived-series-syncing.html).
This is nothing the team does/needs.
If at all - then this is for the release team when opening a new release.
Remove this line please

2021-08-17 14:35 UTC, mirespace commented on Syncs.md
> +A list of packages that maybe can be considered for syncing in the ondevelopment series (impish at the moment of writting) can be found [here](https://launchpad.net/ubuntu/impish/+localpackagediffs).
Yes, for that reason the "maybe" word is ahead. 

It was an attempt to incorporate the very beginning of the task itself: the list of merge opportunities (as you noticed, Bryce's mail).  I feel it's not referenced anywhere in the UMH, and I think it should be (I'm not asking for a detailed explanation of how is it done... I suppose it's well known on the team).

Agree with you in remove the section.

2021-08-17 14:35 UTC, mirespace commented on Syncs.md
> +You can read more about syncing from a parent series on Launchpad [here](https://launchpad.net/+help-soyuz/derived-series-syncing.html).
Ok.

2021-08-17 14:50 UTC, mirespace commented on Syncs.md
> +packages that are as-is in our Ubuntu series (without Ubuntu or upstream modifications and built directly  from Debian source packages in Ubuntu's autobuilders). So, if we find a package that can be
I took the term autobuilders from here: https://wiki.ubuntu.com/DebianImportFreeze

2021-08-17 14:55 UTC, mirespace commented on Syncs.md
> +packages that are as-is in our Ubuntu series (without Ubuntu or upstream modifications and built directly  from Debian source packages in Ubuntu's autobuilders). So, if we find a package that can be
Thank goodness I signed up for the documentation course!

2021-08-18 07:38 UTC, mirespace commented on Syncs.md
> +- Upload the build log (from sbuild or pbuilder) of the Debian package compiled in the Ubuntu release as proof that the new Debian version still compiles in Ubuntu: you cannot upload the complete bui
Fixed. Separated the use of the dch tool and the build of the source package for uploading to the PPA.

2021-08-18 07:39 UTC, mirespace commented on Syncs.md
> +- In the packages overview page: You can check the satus of a concrete architecture build and its buildlog - i.e. the freeipmi amd64 [buildlog](https://launchpad.net/ubuntu/+source/freeipmi/1.6.6-4/+
Done and rewritten a bit.

2021-08-18 07:41 UTC, mirespace commented
New version has been uploaded and ready for review... thanks in advance.

2021-08-18 07:44 UTC, cpaelzer commented on Syncs.md
> +- In the packages overview page: You can check the satus of a concrete architecture build and its buildlog - i.e. the freeipmi amd64 [buildlog](https://launchpad.net/ubuntu/+source/freeipmi/1.6.6-4/+
Better now - thanks

2021-08-18 07:44 UTC, cpaelzer commented on Syncs.md
> +A list of packages that maybe can be considered for syncing in the ondevelopment series (impish at the moment of writting) can be found [here](https://launchpad.net/ubuntu/impish/+localpackagediffs).
ok

2021-08-18 07:48 UTC, cpaelzer commented on Syncs.md
> +You can read more about syncing from a parent series on Launchpad [here](https://launchpad.net/+help-soyuz/derived-series-syncing.html).
ok now

2021-08-18 07:56 UTC, utkarsh2102 requested changes
I'd also prefer a better commit message. Either squash the two together because the commit message of the second one doesn't help much once it's merged. Hope you see what I mean. Let me know if it's not clear. :D

2021-08-18 07:56 UTC, utkarsh2102 commented on Syncs.md
> +
Can we please name this page as `SyncPackage` or something similar?

2021-08-18 07:59 UTC, cpaelzer commented
This is 98% great now, as discussed I'll merge and provide some minor cleanups and extensions as a follow up PR.
Merging this now ...

2021-08-18 07:59 UTC, merged