Update Triage work and integrate most of the wiki content (reduces redundancy)
canonical/ubuntu-maintainers-handbook pull request #42
Opened 2022-02-08 08:20 UTC by cpaelzer

Hi,
while trying to do the simple change of adding the mysql triage steps to the handbook as [suggested by bryce](https://lists.ubuntu.com/archives/ubuntu-server/2022-February/009142.html) I realized we have plenty of outdated and redundant content int he wiki. The UMH is the place we use, review and update more regularly.

This tries to update and unify things accordingly to the place we actually watch (=UMH).
After this PR is discussed and merged the actions to be taken in other places are:

- Wiki: https://wiki.ubuntu.com/ServerTeam/mysql now covered as special case
  in UMH
  => remove the wiki page, replace with a forwarder to the UMH page
- Ubuntu Server Bug Triage - this is a nice general intro (not too complex) and
  suggests the community to help us. I'd keep that, but mention that the
  server-team itself follows a more elaborate and structured process.
  Then I'd add a link to the UMH BugTriage page
- Wiki https://wiki.ubuntu.com/ServerTeam: Ubuntu Server Bug Triage -> process
  Parts of this section are already before my change completely in UMH.
  Others were split and not moved to UMH to be in one place.
  => Remove in wiki
- Wiki https://wiki.ubuntu.com/ServerTeam: Ubuntu Server Bug Triage -> tooling
  This is now in UMH
  => Remove
- gDoc: Weekly bug housekeeping
  UMH now described server-triage-discuss, server-todo, subscribed
  and server-next. Drop the definitions from the doc and link to the UMH page.
  (like with the wiki, reduce redundancy)
- Wiki https://wiki.ubuntu.com/ServerTeam: "Ubuntu Server Packaging"
  This is outdated (trello references) and much better explained in the UMH already
  - how merges work in MergeProposal.md and PackageMerging.md
  - git ubuntu usage in various use cases along the steps outlining what to
    use it for (in most of our files)
  => Replace this section mostly with links to the respective UMH pages

2022-02-08 14:33 UTC, athos-ribeiro approved these changes
Thanks, Christian!

This looks great :)

I added a few suggestions inline

2022-02-08 14:33 UTC, athos-ribeiro commented on BugTriage.md
> +1. Anything that, if the bug turns out to valid, is something that would be under the *~ubuntu-server* remit to fix (common use
```suggestion
1. Anything that, if the bug turns out to be valid, is something that would be under the *~ubuntu-server* remit to fix (common use
```

2022-02-08 14:33 UTC, athos-ribeiro commented on BugTriage.md
> +4. If the bug is assigned to someone on our team, leave it subscribed. No need to subscribe, and feel free to unsubscribe.
Could we say "and feel free to unsubscribe the team." here just to be even more explicit?

2022-02-08 14:33 UTC, athos-ribeiro commented on BugTriage.md
> +This is organized internally int he teams Jira and automation will create
```suggestion
This is organized internally in the team's Jira and automation will create
```

2022-02-08 16:31 UTC, bryceharrington requested changes
A few spelling fixes, but overall a good improvement to unify the mysql triaging info from wiki.

2022-02-08 16:31 UTC, bryceharrington commented on BugTriage.md
> +  well by:
Less wordy to say "- in addition, help Debian when appropriate by:"

2022-02-08 16:31 UTC, bryceharrington commented on BugTriage.md
> +  - If your create a PR for Ubuntu that can be uses almost as-is consider
s/your/you/
s/uses/used/

2022-02-09 10:18 UTC, cpaelzer commented on BugTriage.md
> +4. If the bug is assigned to someone on our team, leave it subscribed. No need to subscribe, and feel free to unsubscribe.
Thanks - updated

2022-02-09 10:18 UTC, cpaelzer commented on BugTriage.md
> +1. Anything that, if the bug turns out to valid, is something that would be under the *~ubuntu-server* remit to fix (common use
Thanks - updated

2022-02-09 10:19 UTC, cpaelzer commented on BugTriage.md
> +This is organized internally int he teams Jira and automation will create
Thanks - updated

2022-02-09 10:20 UTC, cpaelzer commented on BugTriage.md
> +  well by:
Thanks - updated

2022-02-09 10:21 UTC, cpaelzer commented
All feedback I got so far is integrated now, requesting re-reviews

2022-02-09 15:17 UTC, mirespace requested changes
Hi Christian!

First of all, thank you for your work, as the sync for the server-todo tag, for example, was a pending task of mine :(.

I have a suggestion and a pair of inline comments. 

The suggestion is: Could we be more specific about the meaning of 'Raise with the team'? I understand that is the "Awareness of the Triage" section plus saying it in the StandUp, but this is because I know it, not because I can find that information somewhere.

2022-02-09 17:43 UTC, bryceharrington approved these changes

2022-02-09 21:06 UTC, athos-ribeiro approved these changes

2022-02-09 21:13 UTC, utkarsh2102 approved these changes

2022-02-10 08:20 UTC, cpaelzer commented on BugTriage.md
>    - If the issue affects the development release, it is a merge
The details of that board/LP approach are for a different file and different PR. But indeed it needs to talk about "Launchpad bugs" for merges nowadays.

Also added details about "raising the issue" as you requested

2022-02-10 09:28 UTC, mirespace approved these changes
Thanks, Christian!  +1!

2022-02-10 10:29 UTC, merged