Added Salsa dual-maintenance document
canonical/ubuntu-maintainers-handbook pull request #49
Opened 2022-03-09 17:59 UTC by lvoytek

2022-03-30 07:02 UTC, utkarsh2102 commented
Probably needs a rebase for the last commit or something?

2022-03-31 08:22 UTC, cpaelzer commented
There are some generalizations which are not necessarily true. I'll add a few hints inline ...

2022-03-31 08:32 UTC, cpaelzer requested changes
I'd like to see that we make it clear that this model is not "the one and only" it is just one example of many. I hope my suggestions help with that.

2022-03-31 08:32 UTC, cpaelzer commented on SalsaDualMaintenance.md
> +Some packages for Ubuntu are maintained simultaneously using git ubuntu and [Debian Salsa](https://salsa.debian.org).
Please add something like "this pages outlines the model used in mysql and maybe other packages later on".

2022-03-31 08:32 UTC, cpaelzer commented on SalsaDualMaintenance.md
> +
Add something like "Other packages with dual maintenance and sharing most of the outlined behavior, but not following it exactly are: qemu , dpdk"

2022-03-31 08:32 UTC, cpaelzer commented on SalsaDualMaintenance.md
> +Dual maintenace is done such that git ubuntu acts as the primary source of truth for the Ubuntu package through git ubuntu. Meanwhile, the ubuntu/devel branch on Salsa should be synthesized from git
"This particular style of ..." dual maintenance

2022-03-31 08:32 UTC, cpaelzer commented on SalsaDualMaintenance.md
> +
I'd not yet want to add full descriptions of the different styles, but we could make qemu/dpdk a bullet list and add a one line summary for how they are different, that would be like:

- qemu: Neither git-ubuntu nor salsa are dominant - Long term Ubuntu delta is submitted to Debian and becomes part of build-time procedure which generates `d/control` and changes d/rules behavior. This isn't useful of short-term one off patches, but helps a lot to have less churn on merges.
- dpdk: This is primarily managed in salsa and whenever possible Ubuntu is just a sync. All new changes are proposed and committed to the main branch in salsa and cherry picked from there wherever needed. Later in the life-cycle MRE uploads are distribution specific and happen via git-ubuntu.

2022-03-31 16:23 UTC, lvoytek commented on SalsaDualMaintenance.md
> +Dual maintenace is done such that git ubuntu acts as the primary source of truth for the Ubuntu package through git ubuntu. Meanwhile, the ubuntu/devel branch on Salsa should be synthesized from git
done, thanks for the feedback

2022-04-01 06:55 UTC, cpaelzer commented on SalsaDualMaintenance.md
> +Dual maintenace is done such that git ubuntu acts as the primary source of truth for the Ubuntu package through git ubuntu. Meanwhile, the ubuntu/devel branch on Salsa should be synthesized from git
Thanks, I'm resolving this conversation - let me know what you think of the other two.

2022-04-01 14:19 UTC, lvoytek commented on SalsaDualMaintenance.md
> +
Added these two in an additional packages area

2022-04-25 14:31 UTC, basak commented on SalsaDualMaintenance.md
> +When a merge request is made to ubuntu/devel in Salsa the commits should be cherry-picked onto ubuntu/devel in git ubuntu then tested from there. Once the merge request is reviewed in Salsa and confi
I'm not sure about this, but let's leave it as-is for now, and deal with it when we get there.

2022-05-03 20:33 UTC, lvoytek commented on SalsaDualMaintenance.md
> +This particular style of dual maintenace is done such that git ubuntu acts as the primary source of truth for the Ubuntu package through git ubuntu. Meanwhile, the ubuntu/devel branch on Salsa should
Yeah the wording was I bit weird, updated

2022-05-03 20:34 UTC, lvoytek commented on SalsaDualMaintenance.md
> +Finally, add a commit to the Debian branch updating the changelog to a new version with entries for each logical change. The branch can then be submitted for review in Salsa.
Alright, I added some more depth on logical changes going into debian

2022-05-03 20:36 UTC, lvoytek commented
> Sorry this has taken me so long to get back to. It's not good for it to have dragged on so long. Some minor comments inline. Feel free to adopt or leave as you wish. No need for a further review after this - just go ahead and merge when you're happy please.

Thanks for the review. The changes should be good to go. I don't have write permissions for the repository though

2022-05-04 13:10 UTC, merged