Use the imperative mood in changelog messages
canonical/ubuntu-maintainers-handbook pull request #59
Opened 2022-08-26 11:39 UTC by basak

Best practice is for commit messages and changelog messages to use the imperative mood in the present tense. See for example https://cbea.ms/git-commit/#imperative. This is what I've always done anyway, but Utkarsh points out that then it should be in our guide: https://code.launchpad.net/~racb/ubuntu/+source/ppp/+git/ppp/+merge/428546

2022-08-26 11:39 UTC, basak commented
FWIW, I used the web UI to create this (trivial) PR, and it seemed to create a branch here rather than in a personal fork, with no option to do otherwise.

2022-08-26 11:44 UTC, utkarsh2102 requested changes
Hellu, this looks good. I wonder if you should also mention about the "imperative mode" of language whilst writing commit messages somewhere?

That said, I have a nit below.

2022-08-26 11:44 UTC, utkarsh2102 commented on PackageMerging.md
> +      * Drop Changes:
Thanks, this looks good. But there are more instances of that:
```
$ grep -rnw "Dropped" 
Concepts.md:283:      * Dropped changes, included in Debian:
PackageMerging.md:414: * Save the commit message from `1aed93f` for later including in the `Dropped Changes` section of the new changelog entry.
PackageMerging.md:437:      * Dropped Changes:
```

I think we should fix them all.

2023-05-05 09:46 UTC, basak commented
Thank you for the review! Good idea and catch to grep. One was correct and I've fixed it. The other is a literal quote from an existing historical upload, so I've left that one as-is.

2023-05-05 09:49 UTC, merged