Fix PackageMerging.md to be more clear for users
canonical/ubuntu-maintainers-handbook pull request #63
Opened 2023-01-17 23:22 UTC by MichalMal99

2023-02-03 15:51 UTC, basak requested changes
This looks good! Some comments inline.

Overall, I think the tutorial should be opinionated. So now that we've chosen to not use namespaced tags, we should just eliminate all discussion of them, to keep the tutorial simple for a newcomer.

2023-02-03 15:51 UTC, basak commented on PackageMerging.md
> +tags which explicitly refer to specific bug.
Since this is a tutorial rather than a reference, I suggest not mentioning `--bug` at all, to keep the tutorial simple.

2023-02-03 15:51 UTC, basak commented on PackageMerging.md
> +it.
Let's stick to the tutorial not using tag prefixes, so we should drop `--bug` here as well and not mention it.

2023-02-03 15:51 UTC, basak commented on PackageMerging.md
> +package:
As before, since it's a tutorial we should pick one method, and not mention the alternatives. So let's remove this section.

2023-02-03 15:51 UTC, basak commented on PackageMerging.md
> +number] convention. You will notice that :)
AIUI, we're changing the convention and don't need to mention this.

2023-02-03 15:51 UTC, basak commented on PackageMerging.md
> +was `disco`).
It might be worth mentioning that this name can actually be anything. Otherwise, it might look like it's necessary to have a merge bug exist before starting the merge, which isn't the case.

2023-02-03 15:55 UTC, basak commented on PackageMerging.md
> +was `disco`).
My mistake - the tutorial does tell the reader to create a merge tracking bug at the start, so they will always have one.

2023-02-03 18:37 UTC, MichalMal99 commented on PackageMerging.md
> +number] convention. You will notice that :)
done

2023-02-03 18:55 UTC, MichalMal99 commented on PackageMerging.md
> +package:
Done

2023-02-03 19:01 UTC, MichalMal99 commented on PackageMerging.md
> +tags which explicitly refer to specific bug.
Done

2023-02-03 19:01 UTC, MichalMal99 commented on PackageMerging.md
> +it.
Done

2023-03-14 10:20 UTC, cpaelzer commented on PackageMerging.md
> -    $ git ubuntu merge start ubuntu/devel --bug 1802914
I'm ok making the first read experience simpler.
But we should add a paragraph at the end that in any normal case we'd usually add --bug which will add the namespace prefix to all involved tags like ...
That way we avoid collisions of those tag names and allow easy re-mapping to the related merge bug.

2023-03-14 10:22 UTC, cpaelzer commented on PackageMerging.md
> +
lots of whitespace

2023-03-14 10:23 UTC, cpaelzer commented on PackageMerging.md
> +>
This should be just text (no quote) and the following few all in one raw ``` block ``` please

2023-03-20 17:26 UTC, basak commented
On 14 March 2023 10:20:42 UTC, Christian Ehrhardt ***@***.***> wrote:
>But we should add a paragraph at the end that in any normal case we'd usually add --bug which will add the namespace prefix to all involved tags like ...
>That way we avoid collisions of those tag names and allow easy re-mapping to the related merge bug.

No, based on my poll we concluded that it's mostly your preference and most of the team does *not* do that in the normal case. I don't think options for less common preferences belong in tutorial text.

2023-03-21 09:17 UTC, cpaelzer commented
> No, based on my poll ...

Ah right, you asked about that back then.
I'm biased by using it all the time, but I agree that by keeping this simple it will work better.
Ack to no section mentioning --bug at the end (yet).

2023-03-21 09:26 UTC, cpaelzer commented on PackageMerging.md
> +was `disco`).
I like what you have, but there might be more optimization potential:
>  "(that time when we did that merging the current ubuntu devel was `disco`)."

Suggestion: "that time when we did that merging" -> "In the example below doing a `merge`"
Already good good: "the current ubuntu devel was `disco`"
Maybe add: "and the merge bug for the case was `1802914`" 
Then we'd have the full string explained and all elements would be visually recognizable.
""

2023-03-21 09:41 UTC, cpaelzer requested changes
We did fix up a few things live together a few others have been raise as comments here.
I feel we are almost there \o/

2023-03-21 09:41 UTC, cpaelzer commented on PackageMerging.md
> +Get all commit hashes since old/debian using:
Suggestion: "and check the summary what they changed using" ?

2023-03-21 09:41 UTC, cpaelzer commented on PackageMerging.md
> +So to sum up, if you see any commit with metadata like changelog or
This is a duplicate of "Delete changelog, maintainer" how about extending the above and dropping yours.

"Delete changelog, maintainer" -> "Delete any commit only changing metadata like changelog, maintainer"

2023-03-21 09:41 UTC, cpaelzer commented on PackageMerging.md
> +So to sum up, if you see any commit with metadata like changelog or
And drop the paragraph added below then (which is the duplicate)

2023-03-21 09:41 UTC, cpaelzer commented on PackageMerging.md
> +10. `git diff split/(use autocomplete <tab> to autocomplete version)`
you do not know what this auto-completes for, how about "git diff split/<version>" ?

2023-03-21 09:41 UTC, cpaelzer commented on PackageMerging.md
> +9. `git rebase -i old/debian`
Sticking to your format, add "-> drop metadata changes and reorder/merge/split commits"

2023-03-21 09:41 UTC, cpaelzer commented on PackageMerging.md
> +12. `git tag` -> check if the new tag exists
How about: `git show logical/<version>`

2023-03-21 09:41 UTC, cpaelzer commented on PackageMerging.md
> +16. If there is problem with working directory which is not clean and
16 is not cheat sheet level info - remove?

2023-03-23 09:28 UTC, cpaelzer requested changes
some changes done live, very minimal left

2023-03-23 09:28 UTC, cpaelzer commented on PackageMerging.md
> -    $ git push kstenerud $(git tag |grep "^lp1802914" | xargs)
accidental delete?

While bringing it back, replace kstenerud with <your-git-remote> or such

AND
we no more want the grep, that was for --bug only and is no more needed.
This no more works.

simple form no more using --bug would be
$ git push <your-git-remote> old/ubuntu old/debian new/debian reconstruct/<version> logical/<version> split/<version>

2023-03-23 09:32 UTC, cpaelzer approved these changes
After some iterations we reached a great form.
There always is and will be things to bikeshed or improve, but this helps - especially new starters - by simplifying the process of merges using the simpler form without --bug.
Thanks!

2023-03-23 09:32 UTC, merged