PackageMerging.md: use --decorate option if we want tag names in git log
canonical/ubuntu-maintainers-handbook pull request #66
Opened 2023-02-23 17:55 UTC by ogayot

By default, git-log only shows tags (i.e., decorations) if stdout is redirected to a terminal.  Since we pipe the output of git-log to grep to find the list of recent tags, we need to pass the --decorate option.

2023-02-23 18:36 UTC, basak requested changes
Thank you for the suggestion!

Instead of putting `--decorate` everywhere it is needed, we have it as a recommendation in `Setup.md`, under the Git section. For those who follow the recommendation, telling them to use `--decorate` every time is spurious. So I'm not sure we want to do that here as-is.

On the other hand, I think a note mentioning and linking to that recommendation would be fine instead, if you want to do that?

2023-02-23 22:15 UTC, basak commented
> we have it as a recommendation

A recommendation to adjust the configuration to make it default, I mean.

2023-05-05 10:14 UTC, basak commented
Thank you for taking the time to think about and propose improvements to the handbook!

Our team has just discussed this. We think that if we include the option like this for every configuration option we recommend, the rest of the documentation would become unwieldy. So in this case we concluded that it would be inappropriate to take this change.

2023-05-05 10:14 UTC, closed without merging

2023-05-05 10:16 UTC, ogayot commented
> Thank you for taking the time to think about and propose improvements to the handbook!
> 
> Our team has just discussed this. We think that if we include the option like this for every configuration option we recommend, the rest of the documentation would become unwieldy. So in this case we concluded that it would be inappropriate to take this change.

Thanks @basak, Sorry I forgot to follow up at the time. Your decision makes sense to me!