Add information about the control file to Concepts.md
canonical/ubuntu-maintainers-handbook pull request #68
Opened 2023-02-28 18:55 UTC by MichalMal99

New information with descriptions of the fields from the d/control file has been added to the Concepts.md. That information is compressed and helps to gain basic knowledge of the debian/control.

2023-02-28 23:14 UTC, utkarsh2102 requested changes
Why not just point to https://www.debian.org/doc/manuals/maint-guide/dreq.en.html#control? That's supposed to be the "official" docs. :)

2023-03-01 10:49 UTC, MichalMal99 commented
Hello Utkarsh! Thank you for your comment. There is an official document, but I want to outline everything in the handbook without going into too much detail so that users can find more information elsewhere (I can attach that link at the end). The goal of that handbook is to assist newcomers in adjusting to the team as well as the overall workflow and process, which is why audience is the first thing we consider here. I suppose that if this handbook were only for experienced team members, we would not create it at all, because they know what to look for and where to find specific information from other resources, but we collect here our points of view and write them down for people who joined (and obviously not only) and do not know where to find specific information or what is more important from the bunch of information. Each one receives the knowledge in a different way, which is why it's important to let everyone explain how they understand a specific topic. (For example, at the end, I've included a "Things to keep in mind..." section based on my previous experience and thought it was worth noting for the future. Moreover, outlining the most important information for first-time readers is not so overwhelming, and when they assimilate the basics, it's easier to go deeper into a particular topic.
To sum up, I would leave everything as-is and moreover add the link to the official doc at the end for further reading. What do you think about it?

2023-03-02 09:02 UTC, cpaelzer requested changes
thanks, not yet where I wanted it. Ping me again once improved

2023-03-02 09:02 UTC, cpaelzer commented on Concepts.md
> +Some of the fields are less descriptive and we can cover a bit of them.
Actually we are not even talking about the "most important" more like, "here just a few examples"

2023-03-02 09:02 UTC, cpaelzer commented on Concepts.md
> +Lists packages that conflict with this one, for example by containing
Just pick up to three field as example, describe them shortly - the link to the full debian definition will do the rest.
It only is in the UMH to make everyone aware they do exist and where to find info about them.

2023-03-02 09:02 UTC, cpaelzer commented on Concepts.md
> +Thing to keep in mind while proposing something to the package:
while -> when

2023-03-02 09:02 UTC, cpaelzer commented on Concepts.md
> +to the git repo is pointless.
not yet greta, we will re-eval once the rest is cleaned up

2023-03-02 19:00 UTC, MichalMal99 commented
Done

2023-03-07 10:15 UTC, cpaelzer requested changes
round #2 - fight

2023-03-07 10:15 UTC, cpaelzer commented on Concepts.md
> +to maintainer whose email is given in that field.
"the maintainer"

2023-03-07 10:15 UTC, cpaelzer commented on Concepts.md
> +to maintainer whose email is given in that field.
You might want to drop "Source" and "Depends" but add "VCS" instead.
The reason is that we wanted this to help "who/where to contact" for
- maintainer we can say to talk to them (you have that)
- for VCS we can state that there you find code and might propose a PR if on salsa
- for homepage (you mention it) we can say we find more contact or subject matter experts there

So these three would be great to have, the rest is covered by the link.

Maybe
"Here are just a few examples of the most common tags:"
to
"Here are just a few examples that help you who to contact if in doubt (which is a typical beginners question):"

2023-03-07 10:15 UTC, cpaelzer commented on Concepts.md
> +Thing to keep in mind when proposing something to the package:
Thing ... Drop this sentence, it is odd here

2023-03-07 10:15 UTC, cpaelzer commented on Concepts.md
> +Source: ipmitool
Move the example up - it is good, but it will help to be before the file explanations

2023-03-07 10:15 UTC, cpaelzer commented on Concepts.md
> +What we see above is part of the debian/control file of the ipmitool
Duplicate  - you explain it above at the field (which is good) - do not explain it again here.
Most of what you have here is great - carry what you really like up to the per field explanations.

2023-03-07 10:15 UTC, cpaelzer commented on Concepts.md
> +E.g., we want to propose autopkgtests which are not present in Debian,
Use full "For example .." and I like to have a "apply this" section at the end - this is good.

2023-03-07 10:15 UTC, cpaelzer commented on Concepts.md
> +ipmitool) is developed in Git, but there is also the maintainer from
(in this case
￼ipmitool) - that is clear it is the example

2023-03-07 10:15 UTC, cpaelzer commented on Concepts.md
> +ipmitool) is developed in Git, but there is also the maintainer from
why ", but there is also the maintainer from" there always is.
But implies something and it seems missing here.

2023-03-07 10:15 UTC, cpaelzer commented on Concepts.md
> +ipmitool) is developed in Git, but there is also the maintainer from
That is you secenario:
For example - we want to propose autopkgtests which are not present in Debian, but they are present in Ubuntu.
Does this go to upstream, or Debian git or the maintainer?

2023-03-07 10:15 UTC, cpaelzer commented on Concepts.md
> +is pointless, because in that case, no one else apart from Debian
calrify "the git" - it is not salsa, it is upstream - if packaging is there it is actually the right git - but in this case it has no proposal function, that is why you fall back to mail.

Consider the order:
1. where? -> Debian or Upstream based on what you change
2. how? -> Debian bug / Salsa PR / email maintainer group / email maintainer (based on the situation)

2023-03-09 09:12 UTC, cpaelzer commented on Concepts.md
> +Source: ipmitool
done

2023-03-09 09:13 UTC, MichalMal99 commented on Concepts.md
> +.changes files that control the installation of uploaded files.
thanks, done

2023-03-09 09:14 UTC, MichalMal99 commented on Concepts.md
> +Each control file contains a number of fields. Each field begins with a
thanks, done

2023-03-09 09:14 UTC, MichalMal99 commented on Concepts.md
> +The tags are quite descriptive and to sum them up after checking the
thanks, done

2023-03-09 09:14 UTC, MichalMal99 commented on Concepts.md
> +Some of the fields are less descriptive and we can cover a bit of them.
thanks, done

2023-03-09 09:14 UTC, MichalMal99 commented on Concepts.md
> +Lists packages that conflict with this one, for example by containing
thanks, done

2023-03-09 09:14 UTC, MichalMal99 commented on Concepts.md
> +Thing to keep in mind while proposing something to the package:
thanks, done

2023-03-09 09:14 UTC, MichalMal99 commented on Concepts.md
> +to maintainer whose email is given in that field.
thanks, done

2023-03-09 09:14 UTC, MichalMal99 commented on Concepts.md
> +E.g., we want to propose autopkgtests which are not present in Debian,
thanks, done

2023-03-09 09:15 UTC, MichalMal99 commented on Concepts.md
> +is pointless, because in that case, no one else apart from Debian
thanks, done

2023-03-09 09:15 UTC, MichalMal99 commented on Concepts.md
> +Thing to keep in mind when proposing something to the package:
thanks, done

2023-03-09 09:37 UTC, cpaelzer requested changes
as discussed

2023-03-09 09:37 UTC, cpaelzer commented on Concepts.md
> +tag such as Package or Version.
maybe
tag followed by a Colon such as `Package:` or `Version:`.

2023-03-09 09:37 UTC, cpaelzer commented on Concepts.md
> +We can find more subject matter experts there and some helpful information.
"We can" -> "There we might" ?

2023-03-09 09:37 UTC, cpaelzer commented on Concepts.md
> +There you can find a code and propose a PR, but to do that in this
"a code" -> "the code"

2023-03-09 09:37 UTC, cpaelzer commented on Concepts.md
> +particular example related to tests, salsa must be present.
"related to tests, salsa must be present. In the example, we can easily spot the entry, which tells us that the
 package is developed in git, so there is no salsa."

"related to autopkg tests, the packaging must be part of it (not just the source) and it must allow opening pull requests (PRs) against it. In the example above, we can easily spot the entry, which tells us that the package is developed in git, even with the debian/* content, but there is no way to open and discuss PRs there."

2023-03-09 09:37 UTC, cpaelzer commented on Concepts.md
> +is pointless. In that case, no one else apart from Debian
pointless -> impossible

2023-03-09 09:37 UTC, cpaelzer commented on Concepts.md
> +There is advice to consider.
"There is advice to consider." -> "Let us play through an example submitting autopkgtest changes:"

2023-03-09 09:37 UTC, cpaelzer commented on Concepts.md
> +(Jörg Frings-Fürst), not submit it to the upstream git repo, because autopkgtests
Maybe break that into bullet points showing the steps of consideration
1. since it is a autopkgtest upstream won't care, so submit it to Debian
2. to get it to Debian we can't submit a PR on the git, so consider mails/bugs
  2.1 Each package is different, some prefer mails, some bugs, some PRs - worst case you have to find out by trying or asking 
3. Depending on the case you might contact the maintainer, file a bug or both

2023-03-09 09:37 UTC, cpaelzer commented on Concepts.md
> +Check if a bug like that exists:
"already exists" is what you mean

Move this part up as 3.1 please

2023-03-09 16:29 UTC, MichalMal99 commented on Concepts.md
> +Each control file contains a number of fields. Each line begins with a
done, thanks

2023-03-09 16:29 UTC, MichalMal99 commented on Concepts.md
> +tag such as Package or Version.
done, thanks

2023-03-09 16:29 UTC, MichalMal99 commented on Concepts.md
> +We can find more subject matter experts there and some helpful information.
done, thanks

2023-03-09 16:29 UTC, MichalMal99 commented on Concepts.md
> +There you can find a code and propose a PR, but to do that in this
done, thanks

2023-03-09 16:29 UTC, MichalMal99 commented on Concepts.md
> +particular example related to tests, salsa must be present.
done, thanks

2023-03-09 16:30 UTC, MichalMal99 commented on Concepts.md
> +is pointless. In that case, no one else apart from Debian
done, thanks

2023-03-09 16:30 UTC, MichalMal99 commented on Concepts.md
> +There is advice to consider.
thanks, done

2023-03-09 16:31 UTC, MichalMal99 commented on Concepts.md
> +Attach the debdiff to the bug report you created.
thanks, done

2023-03-09 16:32 UTC, MichalMal99 commented on Concepts.md
> +
thanks, done

2023-03-09 16:32 UTC, MichalMal99 commented on Concepts.md
> +How do we propose our tests to Debian?
thanks, done

2023-03-09 16:36 UTC, MichalMal99 commented on Concepts.md
> +What to do if there is a salsa?
thanks, done

2023-03-09 16:38 UTC, MichalMal99 commented on Concepts.md
> +If not, use the second link to open a bug. Follow the steps listed
thanks, done

2023-03-09 16:43 UTC, MichalMal99 commented on Concepts.md
> +Check if a bug like that exists:
thanks, done

2023-03-09 16:44 UTC, MichalMal99 commented on Concepts.md
> +(Jörg Frings-Fürst), not submit it to the upstream git repo, because autopkgtests
thanks, done

2023-03-14 09:33 UTC, cpaelzer commented on Concepts.md
> +package is developed in git, so there is no salsa.
"so there is no salsa"
->
"but not hosted on [salsa](https://salsa.debian.org/)"

2023-03-14 09:33 UTC, cpaelzer commented on Concepts.md
> +<br>
html magic ??

2023-03-14 09:34 UTC, cpaelzer commented on Concepts.md
> +3. Depending on the case you might contact the maintainer, file a bug or both.<br>
more html magic

2023-03-14 09:34 UTC, cpaelzer commented on Concepts.md
> +If not, consider creating one using the second link from above.
does this need to be indented differntly?

2023-03-14 10:12 UTC, cpaelzer commented on Concepts.md
> +package is developed in git, so there is no salsa.
fixed together

2023-03-14 10:13 UTC, cpaelzer commented on Concepts.md
> +<br>
fixed together

2023-03-14 10:13 UTC, cpaelzer commented on Concepts.md
> +If not, consider creating one using the second link from above.
fixed together

2023-03-14 10:14 UTC, cpaelzer commented
In the current form I think this can be helpful to others later on.
Thanks!
No need to re-iterate many more times - merging after the fixup we created together.

2023-03-14 10:14 UTC, merged