Adding Git section, bug reference field and updating section names related to Package Merges
canonical/ubuntu-maintainers-handbook pull request #86
Opened 2023-07-13 09:32 UTC by mirespace

While shadowing Christian on a Patch Pilot session, I realized that he was using a different template for being used in the MP reviews.

I think that template covers more aspects of the review process, so I'm updating it here accordingly.

2023-07-13 09:57 UTC, cpaelzer requested changes
Hi,
LGTM but i have some minor requests now that you want to make my content more official :-)

2023-07-13 09:57 UTC, cpaelzer commented on MergeProposalReview.md
>    - [ ] no further upstream version to consider
I guess that should better be
  `no further upstream version/changes to consider`
as this isn't limited to just versions.

2023-07-13 09:57 UTC, cpaelzer commented on MergeProposalReview.md
>    - [ ] debian changes look safe
you know what I mean with `no upstream changes that need adaptation` and `debian changes look safe`.

But do you think someone reading it the first time will get that this is about e.g. our delta or Ubuntu design decisions in general and if it will play well with the changes coming from Debian/Upstream?

Putting it in UMH I wonder if we should add a few more words here?
WDYT?

2023-07-13 09:57 UTC, cpaelzer commented on MergeProposalReview.md
> +  - [ ] testcases added ir not needed for this
ir -> or

needed -> strictly required

2023-07-13 11:59 UTC, mirespace commented on MergeProposalReview.md
>    - [ ] debian changes look safe
I completely agree :). I made a few changes more in that sense

2023-07-13 12:04 UTC, mirespace commented
Hi Christian,

thankyou . Since we were making improvements, I have moved the 'update-maintainer has been run' outside the changelog and related to merges, as it has more sense to me (not related directly with the changelog).

If the rephrasing is not so well (no precise enough/correct or too large) ... I'll make more attempts!

2023-07-14 08:32 UTC, cpaelzer commented
> If the rephrasing is not so well (no precise enough/correct or too large) ... I'll make more attempts

No, I'm fine now.
This is a clear improvement over the former and so I'll merge it.
If anyone has more suggestions ideas that can go to a future improvement PR.

2023-07-14 08:32 UTC, cpaelzer approved these changes

2023-07-14 08:32 UTC, merged