DistroSkillTree: init commit
canonical/ubuntu-maintainers-handbook pull request #91
Opened 2023-08-27 22:36 UTC by mitchdz

2023-08-29 17:57 UTC, rpocase requested changes
Lastly - where does this show up in the guide tree? If it's a subpath, I'd recommend putting it under a new directory "Reference/Explanations/Path to Distro upload rights". This page should be linked to from the root index as a quick reference point.

2023-08-29 17:57 UTC, rpocase commented on DistroSkillTree/README.md
> +# Generation
This should be at the end since the focus is really on providing a learning method.

2023-08-29 17:57 UTC, rpocase commented on DistroSkillTree/README.md
> +This page exists to show a visual diagram of a path to get more permissions
The wording here feels a bit awkward. Maybe `This page contains an interactive chart for navigating paths to obtaining permissions to upload changes to Ubuntu archive. This can be used as a model to help build an application for x, y, z`

2023-08-29 17:57 UTC, rpocase commented on DistroSkillTree/README.md
> +![Skill Tree](./packaging.svg)
The way this is linked makes it not interactive, which defeats a large purpose of the tool (links to relevant docs). Can this be updated? I believe this requires some inline html on GitHub, but don't have a reference handy.

2023-08-29 18:03 UTC, mitchdz commented on DistroSkillTree/README.md
> +![Skill Tree](./packaging.svg)
I did a quick search and didn't notice a way to have the .svg file preserve links. The preview is mostly just for that, to preview the document. I'll take a look and see if I can mess around and get embedded links to work, but my gut says Github probably doesn't like that.

2023-08-29 19:38 UTC, mitchdz commented on DistroSkillTree/README.md
> +![Skill Tree](./packaging.svg)
Yeah it appears github doesn't allow those interactive elements.

We could host the interactive `*.svg` on a website and link that with html, but I feel like removing the preview and telling the user the download the `*.svg` and open it in a browser is a better alternative. What do you think?

2023-08-29 20:48 UTC, rpocase commented on DistroSkillTree/README.md
> +![Skill Tree](./packaging.svg)
That's a tiny bit of friction that I think makes it non-obvious. Longer term, I think a lot of this documentation is going into shiny new place that WOULD support HTML. A good alternative for now would be to use [?santize=true](https://github.com/potherca-blog/StackOverflow/blob/master/question.13808020.include-an-svg-hosted-on-github-in-markdown/readme.md) to force the image to open in a new tab when you click on it. Opening image in a new tab works, but is less intuitive for a reader.

2023-08-30 10:57 UTC, rpocase commented
Reiterating original top level comment - we should restructure the location to follow [diataxis](https://diataxis.fr/) (specifically, this is a Reference). The primary docs aren't currently in that organization, but incremental migration is the only way to get there.

2023-08-30 11:16 UTC, dviererbe commented
I don't know if you are aware, but GitHub does support [Mermaid diagrams](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams#creating-mermaid-diagrams)

Although it probably takes some time to convert a `d2` diagram to a `mermaid` diagram (or may even be attached to some limitations), it removed the step of running the tool and updating a svg graphic every time the diagram source changes.

2023-08-30 11:30 UTC, dviererbe commented
> I did a quick search and didn't notice a way to have the .svg file preserve links. The preview is mostly just for that, to preview the document. I'll take a look and see if I can mess around and get embedded links to work, but my gut says Github probably doesn't like that.

Using `mermaid` would also solve your embedded link problem, for example:

```
graph TD;
    Debian
    click Debian "https://www.debian.org/doc/debian-policy/"
```
```mermaid
graph TD;
    Debian
    click Debian "https://www.debian.org/doc/debian-policy/"
```

2023-08-30 11:47 UTC, rpocase commented
> 
> Using `mermaid` would also solve your embedded link problem, for example:
> 

That's really cool. I'm +1 to the conversion if mermaid can generate an equivalent model. The embedded link doesn't seem to be working for me. Clicking results in a blocked link with the text "This content is blocked. Contact the site owner to fix the issue." on hover. Any ideas?
![image](https://github.com/canonical/ubuntu-maintainers-handbook/assets/3418099/8b5f2b6e-28b7-4237-863a-83d88230b1f6)

2023-08-30 11:49 UTC, dviererbe commented
Hmmm... I have a different behavior (using Firefox). Direct clicking does nothing, but right click > "Open Link in new Tab" works

2023-08-30 13:22 UTC, mitchdz commented
> > I did a quick search and didn't notice a way to have the .svg file preserve links. The preview is mostly just for that, to preview the document. I'll take a look and see if I can mess around and get embedded links to work, but my gut says Github probably doesn't like that.
> 
> Using `mermaid` would also solve your embedded link problem, for example:
> 
> ```
> graph TD;
>     Debian
>     click Debian "https://www.debian.org/doc/debian-policy/"
> ```
> 
> ```mermaid
> graph TD;
>     Debian
>     click Debian "https://www.debian.org/doc/debian-policy/"
> ```

Also the original link worked for me on chrome.

2023-08-30 13:26 UTC, mitchdz commented
> Reiterating original top level comment - we should restructure the location to follow [diataxis](https://diataxis.fr/) (specifically, this is a Reference). The primary docs aren't currently in that organization, but incremental migration is the only way to get there.

When the diagram is converted to Mermaid, it will all be a single `README.md` type of file, therefore we could put it in `./Reference/PathToDistroUploadRights.md` (sorry, don't like spaces in my path)

2023-08-30 16:50 UTC, rpocase commented
> sorry, don't like spaces in my path

No problem :). I'm less hung up on exact MD naming and more worried about how it ToC indexing/page naming.

2023-09-12 14:21 UTC, rpocase commented
This is a huge improvement over our original visual aids. The only nit I have is "do enough of these" is a bit arbitrary. Some hover text that gives rough guidance would be good (though it doesn't have to be this PR).

2023-09-12 14:21 UTC, rpocase approved these changes

2023-09-12 14:21 UTC, mitchdz commented
Sorry for the delay. I got side-tracked with some other work. I spent a little bit messing with styles but ultimately decided to just keep the default styles as it seems structured and is easy to read. I worry a little bit about accessibility which I tried to tackle with styles, but honestly I just made it worse. You can see what I was attempting here - https://github.com/mitchdz/testREADME/tree/e6b4faf48c8712c97346bb8cb4978153591d958e Really only the links are the bad part, but the only good solution to that is to change the hyperlinks to a different color which I don't want to do.

2023-09-12 14:32 UTC, mitchdz commented
I left the class/style modifier in the source code, so if in the future we want to play around with it we can just add something like the following to modify the whole diagram. 

Maybe I can add these as comments to play around more easily in the future? Usually not a big fan of holding comments like this.

```Markdown
    %% Classes
    classDef study fill:#99CCFF,color:#000000
    classDef study fill:#fefefe,color:#000000
    classDef task fill:#FFFFFF,color:#000000	
    classDef concept fill:#a7a7a7,color:#000000
    classDef Invisible stroke-width:0,fill:#00000000 

    %% Styles
    style Basics fill:#e6e6e6,color:#000000,stroke:#333
    style InitialStudies fill:#f4f4f4,color:#000000,stroke:#333
    style InitialTasks fill:#f4f4f4,color:#000000,stroke:#333

    style Intermediate fill:#e6e6e6,color:#000000,stroke:#333
    style IntermediateTasks fill:#f4f4f4,color:#000000,stroke:#333

    style Advanced fill:#e6e6e6,color:#000000,stroke:#333
    style AdvancedTasks fill:#f4f4f4,color:#000000,stroke:#333

    style optionalDebian fill:#e6e6e6,color:#000000,stroke:#333

    style Expert fill:#e6e6e6,color:#000000,stroke:#333
    style ExpertTasks fill:#f4f4f4,color:#000000,stroke:#333

    style Duties fill:#e6e6e6,color:#000000,stroke:#333
```

2023-09-12 14:54 UTC, dviererbe approved these changes
Praise: Nice work! Thanks for converting, I know that mermaid can sometimes be a bit fiddly.

2023-09-12 14:54 UTC, dviererbe commented on DistroSkillTree/README.md
> +
Note: I think you removed the style for the `Invisible` class when you removed the other styles.

```suggestion
    %% Styles
    classDef Invisible stroke-width:0,fill:#00000000
    
```

2023-09-12 15:04 UTC, mitchdz commented on DistroSkillTree/README.md
> +
I meant to leave that out, but kept all the style overrides in for future if we want to easily add them back in.

All that does is remove the dot at the start which I kinda like

```mermaid
%% mermaid flowcharts documentation: https://mermaid.js.org/syntax/flowchart.html
%%{ init: { 'flowchart': { 'curve': 'catmullRom' } } }%%
flowchart TD
    classDef Invisible stroke-width:0,fill:#00000000
    Start((" ")):::Invisible
    Start --> |"Path to Distro Contribution"| Basics
    subgraph Basics
    end

```


```mermaid
%% mermaid flowcharts documentation: https://mermaid.js.org/syntax/flowchart.html
%%{ init: { 'flowchart': { 'curve': 'catmullRom' } } }%%
flowchart TD
    Start((" ")):::Invisible
    Start --> |"Path to Distro Contribution"| Basics
    subgraph Basics
    end

```

2023-09-12 15:04 UTC, dviererbe commented on DistroSkillTree/README.md
> +%%{ init: { 'flowchart': { 'curve': 'catmullRom' } } }%%
> I left the class/style modifier in the source code, so if in the future we want to play around with it we can just add something like the following to modify the whole diagram.
> 
> Maybe I can add these as comments to play around more easily in the future? Usually not a big fan of holding comments like this.
> 
> ```
>     %% Classes
>     classDef study fill:#99CCFF,color:#000000
>     classDef study fill:#fefefe,color:#000000
>     classDef task fill:#FFFFFF,color:#000000	
>     classDef concept fill:#a7a7a7,color:#000000
>     classDef Invisible stroke-width:0,fill:#00000000 
> 
>     %% Styles
>     style Basics fill:#e6e6e6,color:#000000,stroke:#333
>     style InitialStudies fill:#f4f4f4,color:#000000,stroke:#333
>     style InitialTasks fill:#f4f4f4,color:#000000,stroke:#333
> 
>     style Intermediate fill:#e6e6e6,color:#000000,stroke:#333
>     style IntermediateTasks fill:#f4f4f4,color:#000000,stroke:#333
> 
>     style Advanced fill:#e6e6e6,color:#000000,stroke:#333
>     style AdvancedTasks fill:#f4f4f4,color:#000000,stroke:#333
> 
>     style optionalDebian fill:#e6e6e6,color:#000000,stroke:#333
> 
>     style Expert fill:#e6e6e6,color:#000000,stroke:#333
>     style ExpertTasks fill:#f4f4f4,color:#000000,stroke:#333
> 
>     style Duties fill:#e6e6e6,color:#000000,stroke:#333
> ```

I think that mermaid styling should not be used if not necessary. GitHub has multiple themes: ![image](https://github.com/canonical/ubuntu-maintainers-handbook/assets/23220572/59ccc0c4-5f14-4754-8b5b-5b466d8dc4b4)
and AFAICT there is no mechanism to change the color depending on the GitHub theme, resulting in bad readability :/

But there are presets that we can choose from: https://mermaid.js.org/config/theming.html

`neutral` looks pretty close to what you wanted to achieve here: https://github.com/mitchdz/testREADME/tree/e6b4faf48c8712c97346bb8cb4978153591d958e

```suggestion
%%{ init: { 'flowchart': { 'curve': 'catmullRom' }, 'theme':'neutral' } }%%
```

2023-09-12 15:08 UTC, mitchdz commented on DistroSkillTree/README.md
> +%%{ init: { 'flowchart': { 'curve': 'catmullRom' } } }%%
This is great to know! I'd like to force a certain style since I do worry about color contrast making accessibility an issue. I tried the neutral theme at https://github.com/mitchdz/testREADME/blob/main/README.md and find the previously opened (purple) hyperlinks are difficult to see with the background, so I would prefer not to use that colorscheme.

2023-09-20 14:27 UTC, rpocase requested changes
Realized I had requests that didn't make it in. This still needs to be made obvious QUICKLY from the landing page. I would personally recommend the following structure change:

* DistroSkillTree -> Reference. Rename README.md to something more appropriate (e.g. path_to_upload_rights.md)
* Add a README.md to ^ that builds the appropriate index
* Add a link in the root README.md that has a link to the upload rights VERY early on (e.g. a sentence at the end of the first paragraph `If you need guidance on where to start, check out the [Path to Distro Upload Rights](Reference/path_to_distro_upload_rights.md) page.`

2023-09-25 13:41 UTC, mitchdz commented
Thanks Robby, I incorporated those changes.

2023-09-25 14:44 UTC, rpocase approved these changes

2023-10-03 14:01 UTC, mitchdz commented
Can this be merged please?

2023-10-04 09:37 UTC, cpaelzer commented
I have discussed this with @rpocase when it was v1 and while there could be endless bikeshedding like "is this the right doc to have this in" or any "shouldn't we also mention ...?" I think there is no better place yet and it is helpful as-is.

All of that can be further improved or move later if needed.

Thanks for you all working together ... +1 and merging

2023-10-04 09:37 UTC, cpaelzer approved these changes

2023-10-04 09:37 UTC, merged