CommittingChanges.md: Clarify upload versioning
canonical/ubuntu-maintainers-handbook pull request #92
Opened 2023-09-04 07:31 UTC by cpaelzer

We have had too many cases where referring to the security wiki page that served as the gold standard was not sufficient. Especially around going ahead via upstream merges and even more so backports and pushing new versions as MREs it needs to be spelled out to avoid common mistakes from re-occuring.

This adds explanatory text and explicit examples for:
- upstream merges going ahead of Debian
- backports of upstream versions (MRE)
- backports from -devel (same on all releases)

2023-09-04 07:31 UTC, cpaelzer commented
We have - in the past - usually referred everyone to https://wiki.ubuntu.com/SecurityTeam/UpdatePreparation#Update_the_packaging and only repeated the same here for readability in one flow. But over the past years there have been so often edge cases that drive people mad that I think they need to be spelled out explicitly. This is a great place to get input from everyone involved (one from each of my squads driving the various cases regularly plus Steve who thankfully brought it up a few days ago on SRU review). Once we fully agree here I suppose we should suggest the same update to https://wiki.ubuntu.com/SecurityTeam/UpdatePreparation#Update_the_packaging or whatever the right place would be once changes to wiki as well as the rewrite of the Ubuntu packaging guide complete.

2023-09-08 13:29 UTC, TheRealFalcon reviewed
Thanks for the information here! Super helpful.

I left some inline comments.

2023-09-08 13:29 UTC, TheRealFalcon commented on CommittingChanges.md
> +While not talking about Ubuntu delta and all it implications, for overall topic awareness it is very helpful to fully read through [Debian control field "Version"](https://www.debian.org/doc/debian-p
I'm not entirely sure what is meant by `Ubuntu delta` here. I think the part before the comma can be removed entirely.

If not, a slight grammar change:

```suggestion
While not talking about Ubuntu delta and all of its implications, for overall topic awareness it is very helpful to fully read through [Debian control field "Version"](https://www.debian.org/doc/debian-policy/ch-controlfields.html#version) as well
```

2023-09-08 13:29 UTC, TheRealFalcon commented on CommittingChanges.md
> +For example, suppose the current version in bionic is `3.3.0-1` and the current version in cosmic is `3.3.0-1ubuntu1`.
I know you didn't write this section, but this entire section along with the table is very confusing to a new-comer. I had to read it like 4 times to figure out what it's trying to say. It doesn't talk about context at all. Just "if this is your old version, here's the new version". But when? Are we talking about devel vs SRU vs backports? Is `cosmic` supposed to be the devel release in this case? It should clearly state that these are version changes in an *already released series*.

It's good you added the link to the debian versioning, but first I think there needs to be an introduction to the `ubuntuX` convention before jumping into this section. The next section you added `Merging from Debian` should probably come first.

2023-09-08 13:29 UTC, TheRealFalcon commented on CommittingChanges.md
> +There are more special cases, especially related to backports (As in backports of new versions via SRU, not as in https://wiki.ubuntu.com/UbuntuBackports).
Thanks for the parenthetical!

2023-09-08 13:29 UTC, TheRealFalcon commented on CommittingChanges.md
> +| Devel  | 2.1-1ubuntu2 | 3.0-0ubuntu1 |
Since we're uploading `3.1`, new should be `3.1-0ubuntu1`, right?

2023-09-08 13:29 UTC, TheRealFalcon commented on CommittingChanges.md
> +* Signal that it is not based on, a potentially existing, Debian version of the same by using `-0` as the Debian packaging revision
Not sure what `a potentially existing` means here

2023-09-08 15:51 UTC, orndorffgrant commented on CommittingChanges.md
> +While not talking about Ubuntu delta and all it implications, for overall topic awareness it is very helpful to fully read through [Debian control field "Version"](https://www.debian.org/doc/debian-p
I think its just meant to say that the debian docs don't include Ubuntu-specific details, but I agree its worded confusingly. Here's another idea for rewording:
```suggestion
While Debian docs won't include Ubuntu specificities, it is helpful to fully read through [Debian control field "Version"](https://www.debian.org/doc/debian-policy/ch-controlfields.html#version) for overall topic awareness.
```

2023-09-08 15:51 UTC, orndorffgrant commented on CommittingChanges.md
> +Most version changes, except _upstream merges_, will follow this format when adding a change in Ubuntu:
Should there be a link here to a definition of _upstream merges_ and why they are a special case?

2023-09-08 15:51 UTC, orndorffgrant commented on CommittingChanges.md
>  | Previous version             | Recommended version                           |
This table essentially always recommends bumping the Y in `ubuntuX.Y`. But if we never bump the X, then how could we end up with a version like `2.0-2ubuntu2` ever?

I added another related question later on, but the general question is "when do we bump X and when do we bump Y in `ubuntuX.Y`?"

2023-09-08 15:51 UTC, orndorffgrant commented on CommittingChanges.md
> +Most version changes, except _upstream merges_, will follow this format when adding a change in Ubuntu:
Aha that is defined below. We might be able to add a link to that header, or add a parenthetical "...upstream merges (described later in this document)..."

2023-09-08 15:51 UTC, orndorffgrant commented on CommittingChanges.md
> +For example, suppose the current version in bionic is `3.3.0-1` and the current version in cosmic is `3.3.0-1ubuntu1`.
I agree. I think we need a short "sequel" to the debian version docs up at the beginning of the section, where we describe what Ubuntu adds. e.g. something explaining "Debian has `[epoch:]upstream_version[-debian_revision]` and Ubuntu is downstream of Debian so we add more parts to get `[epoch:]upstream_version[-debian_revision][ubuntuX.Y]` where `ubuntuX.Y` gets added when .... and X and Y mean ....".

2023-09-08 15:51 UTC, orndorffgrant commented on CommittingChanges.md
> +The version for the new upload to the Ubuntu development is the version from Debian with a suffix of `ubuntu1`
See my question on the table above. Why do we recommend `ubuntu1` here but above in the table we recommend `ubuntu0.1`?

2023-09-08 15:51 UTC, orndorffgrant commented on CommittingChanges.md
> +> Example situation: _Uploading `3.1` to Ubuntu -Devel based with Ubuntu detla rebased onto Debian `3.1-2`_
typo
```suggestion
> Example situation: _Uploading `3.1` to Ubuntu -Devel based with Ubuntu delta rebased onto Debian `3.1-2`_
```

2023-09-08 15:51 UTC, orndorffgrant commented on CommittingChanges.md
> +> Example situation: _Uploading `3.1` to LTS and LTS+1 being more or less identical to what is in -devel in `3.1`_
This looks copy/pasted without updating
```suggestion
> Example situation: _Uploading `3.1` caused a regression, so rolling back to the previous version_
```

2023-09-08 15:51 UTC, orndorffgrant commented on CommittingChanges.md
> +* Add an increment that can be used in subsequent individual per release SRU uploads like `.1`
u-a-t found this final `.1` to be unhelpful since it was rare for a bug to only affect one Ubuntu release, so we dropped it. We could still add a `.1` in that rare case where we'd rather do a release-specific patch instead of delivering a fix to all releases. We might be unique though and not sure if that detail is worth adding here.

2023-09-08 15:51 UTC, orndorffgrant commented on CommittingChanges.md
> +> Example situation: _Uploading `3.1` to LTS and LTS+1 being more or less identical to what is in -devel in `3.1ubuntu2`_
```suggestion
> Example situation: _Uploading `3.1` to LTS and LTS+1 being more or less identical to what is in -devel in `3.1-1ubuntu2`_
```

2023-09-11 07:11 UTC, cpaelzer commented on CommittingChanges.md
> +For example, suppose the current version in bionic is `3.3.0-1` and the current version in cosmic is `3.3.0-1ubuntu1`.
Yeah, for all new sections I added "Example situation" which is way more concise and always follows exactly the related explanation above. Let me rewrite this older section in the same style and add a little intro above (again just like my new sections have it).

Ok, now this section is also explanation -> example -> table.

I should have known what I signed up for trying to make this more helpful, writing it "correctly" and without the problems you had also needs sections for all other cases that are not explained. I tried to just go from what we had to the different backports. But your question made me realize that we also need all others like native packages and no change rebuilds.

I hope I haven't made too many mistakes in those sections. Just a warning, you correctly asked "this is good, but then it misses", but by iterating on making those correct and non-lacking the whole will be a much longer read. I hope that is then not ending up too distracting.

2023-09-11 07:15 UTC, cpaelzer commented on CommittingChanges.md
> +| Devel  | 2.1-1ubuntu2 | 3.0-0ubuntu1 |
Hmm, yeah the tables are never super closely related to the examples in my mind.
I still fixed it to be less confusing and also completed  the example above to be more self contained.

2023-09-11 07:17 UTC, cpaelzer commented on CommittingChanges.md
> +* Signal that it is not based on, a potentially existing, Debian version of the same by using `-0` as the Debian packaging revision
If we'd pick 3.1-1 here then 3.1-1 might now or later exist in Debian.
But that is not what this upload is based on.
Hence the 3.1-1 might "potentially exist", so we pick 3.1-0 to make it clear.

Rephrased to "Signal that it is not based on a Debian packaging version by using `-0` as the Debian packaging revision" and also introduced "Debian packaging revision" a bit better above.

2023-09-11 07:19 UTC, cpaelzer commented on CommittingChanges.md
> +Most version changes, except _upstream merges_, will follow this format when adding a change in Ubuntu:
This section was simplified (and extended with much more slow starting context) not yet hinting at the complex truth that comes later.

2023-09-11 07:20 UTC, cpaelzer commented on CommittingChanges.md
>  | Previous version             | Recommended version                           |
You and James asked for this indirectly above, the sections that explain this and more now exist.
TL;DR: non-SRU uploads

2023-09-11 07:21 UTC, cpaelzer commented on CommittingChanges.md
> +The version for the new upload to the Ubuntu development is the version from Debian with a suffix of `ubuntu1`
This was already fixed by splitting and adding separate sections for "Adding a change in the current Ubuntu development release" and "Adding a change in Ubuntu as a stable release update"

2023-09-11 07:22 UTC, cpaelzer commented on CommittingChanges.md
> +> Example situation: _Uploading `3.1` to Ubuntu -Devel based with Ubuntu detla rebased onto Debian `3.1-2`_
Fixed

2023-09-11 07:24 UTC, cpaelzer commented on CommittingChanges.md
> +> Example situation: _Uploading `3.1` to LTS and LTS+1 being more or less identical to what is in -devel in `3.1`_
Good catch, fixed - but context has changed a bit

2023-09-11 07:26 UTC, cpaelzer commented on CommittingChanges.md
> +* Add an increment that can be used in subsequent individual per release SRU uploads like `.1`
yeah, you are special and I think adding "situations when to consider not doing so" makes this even more pain to read.
Thanks for the thought though.

2023-09-11 07:27 UTC, cpaelzer commented on CommittingChanges.md
> +> Example situation: _Uploading `3.1` to LTS and LTS+1 being more or less identical to what is in -devel in `3.1ubuntu2`_
Ack, fixed

2023-09-11 07:30 UTC, cpaelzer commented
Thank you @TheRealFalcon and @orndorffgrant for the initial pass. I hope it is now even more complete and helpful. Since I needed to add quite some content to resolve your needs I re-requested your review.

2023-09-11 18:28 UTC, TheRealFalcon reviewed
The content itself is mostly all good at this point. I added a number of comments, mostly minor grammar and flow-type things, but there's a few rendering issues and one section that I still found a little confusing related to native packages.

Also, just generally:
`Example situation:` can be probably be replaced with `Example:` throughout. `situation` doesn't really add more meaning or context.

2023-09-11 18:28 UTC, TheRealFalcon commented on CommittingChanges.md
> +| Previous version       | Devel upload  |  SRU upload   |
This table isn't rendering properly.

2023-09-11 18:28 UTC, TheRealFalcon commented on CommittingChanges.md
> +> Example situation: _A package native to Debian (no `-`), getting an Ubuntu change in the devel release `39.3 -> 39.3ubuntu1`
Don't forget to end with `_` to make the italics work.

2023-09-11 18:28 UTC, TheRealFalcon commented on CommittingChanges.md
> +> Example situation: _A package native to Ubuntu (no `-`) and no `ubuntuX` getting an Ubuntu change in the devel release `39.3 -> 39.4`
Don't forget to end with `_` to make the italics work.

2023-09-11 18:28 UTC, TheRealFalcon commented on CommittingChanges.md
> +> Example situation: _A Debian package 3.1-3 needs a rebuild in Ubuntu `3.1-3 -> 3.1-3build1`
Don't forget to end with `_` to make the italics work.

2023-09-11 18:28 UTC, TheRealFalcon commented on CommittingChanges.md
> +splitting or removing binary packages etc. To represent that the upload should:
nit:
```suggestion
splitting or removing binary packages etc. To represent this the upload should:
```

2023-09-11 19:26 UTC, orndorffgrant approved these changes
Thank you for this document! I'm happy that we have all of these scenarios documented when they were previously only known and passed along by the initiated few. This is great.

@TheRealFalcon's review is thorough and I have no more comments on the content.

My only additional comment is that this has grown so much that maybe it deserves it's own page in the handbook?

2023-09-12 08:46 UTC, cpaelzer commented on CommittingChanges.md
> +> Example situation: _A package native to Debian (no `-`), getting an Ubuntu change in the devel release `39.3 -> 39.3ubuntu1`
Good catch, fixed

2023-09-12 08:46 UTC, cpaelzer commented on CommittingChanges.md
> +> Example situation: _A Debian package 3.1-3 needs a rebuild in Ubuntu `3.1-3 -> 3.1-3build1`
Good catch, fixed

2023-09-12 08:47 UTC, cpaelzer commented on CommittingChanges.md
> +> Example situation: _A package native to Ubuntu (no `-`) and no `ubuntuX` getting an Ubuntu change in the devel release `39.3 -> 39.4`
Good catch

2023-09-12 08:51 UTC, cpaelzer commented on CommittingChanges.md
> +| 2.0                          | 2.0ubuntu1            |
As you learn below this is a native package, this is actually one of four valid answers depending whose native pkg it is and where you upload. I'll remove the line here entirely and refer to read that section I added later.

2023-09-12 09:00 UTC, cpaelzer commented on CommittingChanges.md
> +Then the first element in the scheme would make no sense?
I improved the wording with something in between what both of us had - thanks!

2023-09-12 09:11 UTC, cpaelzer commented on CommittingChanges.md
> +| Previous version       | Devel upload  |  SRU upload   |
Found and fixed - thank you!

2023-09-12 09:35 UTC, cpaelzer commented
Thank you both @orndorffgrant and @TheRealFalcon - I think it is now at the level to be useful to you and many others.

> My only additional comment is that this has grown so much that maybe it deserves it's own page in the handbook?

I agree, with the recent growth that deserves a place on its own (even more so since this might be something people refer to even without the former context around it). Done in the most recent push.

To split the page might eventually be even more helpful as it is not server team specific. Foundations is working on updating the [ubuntu packaging guide](https://packaging.ubuntu.com/html/). Once that is done and there is new place and format ready, it might make sense to move the whole new "select a version" page over there and update our links to refer to it. Highlighting @dviererbe for awareness (ask me to move it together with you once your side is ready for this to land - instead of duplicating the content and effort).


I think we have reached a state where this could get a finalizing look by

-  @basak and @vorlonofportland for correctness
-  and another one by @s-makin for general flow and wording.

2023-09-19 12:28 UTC, panlinux commented on README.md
> +   - [Committing Your Changes](VersionStrings.md)
Did you mean to change this to VersionStrings?

2023-09-19 12:34 UTC, panlinux commented on VersionStrings.md
> +One can think of a version number consisting of three segements: `[upstream_version]-[debian_revision]ubuntu[ubuntu_revision]`.
"segements" typo

2023-09-19 12:38 UTC, panlinux commented on VersionStrings.md
> +
This table misses an introduction. The last phrase before it mentions another document section entirely.

I would suggest something like "This table shows the common case for version number updates in the development release:" And perhaps not even mention stable releases yet.

2023-09-19 12:44 UTC, panlinux commented on VersionStrings.md
> +[automatically synced](https://github.com/canonical/ubuntu-maintainers-handbook/blob/main/Syncs.md#why-a-sync-is-better) as thereby that delta would be lost.
Is this URL the correct way to link to another MD document in this tree? Is it because of the anchor `#`? Wouldn't something like [automatically synced](Syncs.md#why-a-sync-is-better) work?

2023-09-19 12:46 UTC, panlinux commented on VersionStrings.md
> +In that case a Ubuntu developer usually regularly [merges the delta](https://github.com/canonical/ubuntu-maintainers-handbook/blob/main/PackageMerging.md#merging)
"an Ubuntu developer"?

2023-09-19 12:52 UTC, panlinux commented on VersionStrings.md
> +Yes that means, from just the version, you can not differentiate between a _native Debian package that was synced_ and a _native package in Ubuntu_
Missind EOL "."

2023-09-19 13:05 UTC, panlinux commented on VersionStrings.md
> +There are more special cases, especially related to backports (As in backports of new versions via SRU, not as in https://wiki.ubuntu.com/UbuntuBackports).
lowercase "(As in backports..." -> "(as in backports...".

2023-09-19 14:58 UTC, s-makin requested changes
Mostly just nits/suggestions, but a few questions on clarity as well

2023-09-19 14:58 UTC, s-makin commented on VersionStrings.md
> +Compare these examples with the _Adding a change in the current Ubuntu development release_ section above.
Can we add a link to the section heading?

2023-09-19 14:58 UTC, s-makin commented on VersionStrings.md
> +| Previous version             | Recommended version                           |
As was suggested above, this table needs to be introduced as it's not clear what the purpose of it it

2023-09-19 14:58 UTC, s-makin commented on VersionStrings.md
> +This is due to the classification as _native_ or _non-native_ package as outlined by the referred [Debian control field version](https://www.debian.org/doc/debian-policy/ch-controlfields.html#version
Is the "native" wording something that exists in Debian (that we can't change)? If this is wording we have control over, it would be ideal to change this away from the "native/non-native" for inclusivity.

2023-09-19 14:58 UTC, s-makin commented on VersionStrings.md
> +Yes that means, from just the version, you can not differentiate between a _native Debian package that was synced_ and a _native package in Ubuntu_
```suggestion
Yes that means, from just the version, you can not differentiate between a _native Debian package that was synced_ and a _native package in Ubuntu_.
```

2023-09-19 14:58 UTC, s-makin commented on VersionStrings.md
> +until the [Debian import freeze](https://wiki.ubuntu.com/DebianImportFreeze) date is met, then this is deactivated to stabilize the upcoming Ubuntu release.
```suggestion
until the [Debian import freeze](https://wiki.ubuntu.com/DebianImportFreeze) date is met, then syncs are deactivated to stabilize the upcoming Ubuntu release.
```

2023-09-19 14:58 UTC, s-makin commented on VersionStrings.md
> +until the [Debian import freeze](https://wiki.ubuntu.com/DebianImportFreeze) date is met, then this is deactivated to stabilize the upcoming Ubuntu release.
At least, I'm assuming that "this" in this context refers to the syncs

2023-09-19 14:58 UTC, s-makin commented on VersionStrings.md
> +As outlined there _" will be automatically imported from Debian where they have not been customized for Ubuntu, that is when the version number of the
Outlined where? This is a bit confusing because you have two links in the previous sentence so it's not clear which one you're referring to

2023-09-19 14:58 UTC, s-makin commented on VersionStrings.md
> +So what if one needs to rebuild a package, for example due to a libarary transition to build against new versions of other packages,
```suggestion
So what if one needs to rebuild a package, for example due to a library transition to build against new versions of other packages,
```

2023-09-19 14:58 UTC, s-makin commented on VersionStrings.md
> +* If there is already a `ubuntuX` suffix there would be no auto-sync anyway, so increment the existing suffix
```suggestion
* If there is already an `ubuntuX` suffix there would be no auto-sync anyway, so increment the existing suffix.
```

2023-09-19 14:58 UTC, s-makin commented on VersionStrings.md
> +but in this situation auto-syncing isn't active anyway and the need for upgradability apply.
```suggestion
but in this situation auto-syncing isn't active anyway and the need for upgradability applies.
```

2023-09-19 14:58 UTC, s-makin commented on VersionStrings.md
> +(see the section _Adding a change in Ubuntu as a stable release update_ above)
```suggestion
(see the section _Adding a change in Ubuntu as a stable release update_ above).
```

2023-09-19 14:58 UTC, s-makin commented on VersionStrings.md
> +There are more special cases, especially related to backports (As in backports of new versions via SRU, not as in https://wiki.ubuntu.com/UbuntuBackports).
```suggestion
There are more special cases, especially related to backports (as in backports of new versions via SRU, not as in https://wiki.ubuntu.com/UbuntuBackports).
```

2023-09-19 14:58 UTC, s-makin commented on VersionStrings.md
> +it will lose all its former version suffix. This is a common practice on some
```suggestion
it will lose all its former version suffixes. This is a common practice on some
```

2023-09-19 14:58 UTC, s-makin commented on VersionStrings.md
> +* Add an increment that can be used in subsequent individual per release SRU uploads like `.1`
```suggestion
* Signal that it is not based on a Debian packaging version by using `-0` as the Debian packaging revision.
* Signal that it was not yet packaged before in this Ubuntu release before via `ubuntu0.`.
* Add a suffix per Ubuntu release like `.22.04`.
* Add an increment that can be used in subsequent individual per-release SRU uploads like `.1`.
```

2023-09-19 14:58 UTC, s-makin commented on VersionStrings.md
> +> Example: _Uploading `3.1` but packaging wise using what is already in LTS and LTS+1, not with all the Ubuntu changes that might be in `3.1-1ubuntu2`_
```suggestion
> Example: _Uploading `3.1` but packaging-wise using what is already in LTS and LTS+1 -- not with all the Ubuntu changes that might be in `3.1-1ubuntu2`_.
```

2023-09-19 14:58 UTC, s-makin commented on VersionStrings.md
> +The new version is independent to the former version of the target release, here an example for 22.04:
```suggestion
The new version is independent of the former version of the target release, here an example for 22.04:
```

2023-09-19 14:58 UTC, s-makin commented on VersionStrings.md
> +But if instead the backport is actually without _meaningful sourceful
What does sourceful mean in this context?

2023-09-19 14:58 UTC, s-makin commented on VersionStrings.md
> +* Add an increment that can be used in subsequent individual per release SRU uploads like `.1`
```suggestion
* Signal that is it basically _identical but backported_ by starting with the same version as the one in the development release.
* Add a `~` to ensure it sorts earlier than the version in -devel.
* Add a suffix per Ubuntu release like `22.04`.
* Add an increment that can be used in subsequent individual per-release SRU uploads like `.1`.
```

2023-09-19 14:58 UTC, s-makin commented on VersionStrings.md
> +> Example: _Uploading `3.1` to LTS and LTS+1 being more or less identical to what is in -devel in `3.1-1ubuntu2`_
```suggestion
> Example: _Uploading `3.1` to LTS and LTS+1 being more or less identical to what is in -devel in `3.1-1ubuntu2`_.
```

2023-09-19 14:58 UTC, s-makin commented on VersionStrings.md
> +The new version is again independent to the former version that was present in the target release.
```suggestion
The new version is again independent of the former version that was present in the target release.
```

2023-09-19 14:58 UTC, s-makin commented on VersionStrings.md
> +> Example: _Uploading `3.1` to LTS and LTS+1 being more or less identical to what is in -devel in `3.1`_
```suggestion
> Example: _Uploading `3.1` to LTS and LTS+1 being more or less identical to what is in -devel in `3.1`_.
```

2023-09-19 14:58 UTC, s-makin commented on VersionStrings.md
> +> Example: _Uploading `3.1` caused a regression, so rolling back to the previous version_
```suggestion
> Example: _Uploading `3.1` caused a regression, so rolling back to the previous version_.
```

2023-09-20 07:20 UTC, cpaelzer commented on README.md
> +   - [Committing Your Changes](VersionStrings.md)
No, this was a search and replace too much - fixed.
Thanks - good catch!

2023-09-20 07:20 UTC, cpaelzer commented on VersionStrings.md
> +One can think of a version number consisting of three segements: `[upstream_version]-[debian_revision]ubuntu[ubuntu_revision]`.
thanks - fixed

2023-09-20 07:29 UTC, cpaelzer commented on VersionStrings.md
> +
You are both right, due to having added much more sections this feels a bit out of context.

I'll move more explanation up into the text, fix the examples to match the table that follows.
I'll remove the mention of SRUs at this stage (I already have the "please read the rest" after the table which is enough.

The only case I need to leave here and say "have a look for details" is in regard to no-change rebuilds.
But for that I added an explanatory statement that now matches the context better.

2023-09-20 07:36 UTC, cpaelzer commented on VersionStrings.md
> +[automatically synced](https://github.com/canonical/ubuntu-maintainers-handbook/blob/main/Syncs.md#why-a-sync-is-better) as thereby that delta would be lost.
Both work and both styles are used already (e.g. in `Syncs.md`), some even linking to old versions.
I've fixed not just mine but all occurrences so that it works well if checked out and read locally or even on PRs.

2023-09-20 07:36 UTC, cpaelzer commented on VersionStrings.md
> +In that case a Ubuntu developer usually regularly [merges the delta](https://github.com/canonical/ubuntu-maintainers-handbook/blob/main/PackageMerging.md#merging)
ack, fixed - thanks!

2023-09-20 07:37 UTC, cpaelzer commented on VersionStrings.md
> +Yes that means, from just the version, you can not differentiate between a _native Debian package that was synced_ and a _native package in Ubuntu_
Was lost in the italics, thanks!

2023-09-20 07:38 UTC, cpaelzer commented on VersionStrings.md
> +| 2.0build1              | 2.0ubuntu1    |  2.0ubuntu1   |
you are just right and nothing else - fixed!

2023-09-20 08:04 UTC, cpaelzer commented on VersionStrings.md
> +| 2.0 (native in Ubuntu)       | 2.1                           |
AFAIK yes,
this is even trickier than you think (2.1 or 3 actually) and I guess the only way is to add more examples.
That is true here and in the "native package" section which I extended both with text and examples.

I hope it is correct now, glad we found something that is even "hard to answer" for us.

2023-09-20 08:05 UTC, cpaelzer commented on VersionStrings.md
> +There are more special cases, especially related to backports (As in backports of new versions via SRU, not as in https://wiki.ubuntu.com/UbuntuBackports).
fixed

2023-09-20 08:05 UTC, cpaelzer commented on VersionStrings.md
> +Version String Format
added

2023-09-20 08:06 UTC, cpaelzer commented on CommittingChanges.md
> +Please see [Version String Format](VersionStrings.md) for details.
The caption above was the same, fixed the same way

2023-09-20 08:07 UTC, cpaelzer commented on VersionStrings.md
> +The following paragraphs first link to the required basics which are shared with Debian.
TIL - it was the former - fixed

2023-09-20 08:08 UTC, cpaelzer commented on VersionStrings.md
> +The `ubuntu` string then marks that all following is related to changes added in Ubuntu.
added, thanks!

2023-09-20 08:08 UTC, cpaelzer commented on VersionStrings.md
> +By everyone abiding to these patterns we can guarantee package upgradability, but also allow that one can derive a lot of the history by just looking at the package version.
Interesting, added

2023-09-20 08:14 UTC, cpaelzer commented on VersionStrings.md
> +In that case a Ubuntu developer usually regularly [merges the delta](https://github.com/canonical/ubuntu-maintainers-handbook/blob/main/PackageMerging.md#merging)
Clarified as "usually at least once per Ubuntu release" for magnitude and slightly moved to match the reading flow.

2023-09-20 08:14 UTC, cpaelzer commented on VersionStrings.md
> +[automatically synced](https://github.com/canonical/ubuntu-maintainers-handbook/blob/main/Syncs.md#why-a-sync-is-better) as thereby that delta would be lost.
fixed

2023-09-20 08:15 UTC, cpaelzer commented on VersionStrings.md
> +* represent that there are Ubuntu changes via `ubuntu1` which also serves as a place increment for further uploads to the development release
If that is upper case, then the above needs to be as well - done both

2023-09-20 08:15 UTC, cpaelzer commented on VersionStrings.md
> +* reflect that it was not yet packaged in Debian (at this point in time) and thereby is not _really_ based on a Debian version by using `-0` as the Debian version suffix.
odd ordering in GH, already fixed

2023-09-20 08:16 UTC, cpaelzer commented on VersionStrings.md
> +After a version of Ubuntu is released, changes to packages follow a slightly different versining scheme which ensures upgradability to later releases and allows to recognize the history of changes fr
fixed

2023-09-20 08:19 UTC, cpaelzer commented on VersionStrings.md
> +* If no `ubuntuX` was present before, then set `ubuntu0.1` which will represent that there was no Ubuntu delta before `0` this upload which is the first to add `.1` a change.
Hmm, this took me a while to accept - but ok. suggestion taken

2023-09-20 08:41 UTC, cpaelzer commented on VersionStrings.md
> +| Previous version             | Recommended version                           |
I have generally reworked the former "Example" with text to "Example in detail:"
I also made the wordy examples match the early tables entries (to build a connection between text and table).
Finally the tables got a header saying "List of these and further related Examples:"

In doing so I added even more example lines to tables, fixed formatting and found a few other minor things.
Thanks @panlinux and @s-makin for bringing this up.

2023-09-20 08:42 UTC, cpaelzer commented on VersionStrings.md
> +This is due to the classification as _native_ or _non-native_ package as outlined by the referred [Debian control field version](https://www.debian.org/doc/debian-policy/ch-controlfields.html#version
It is a defined term in the Debian policy.
The second link already is the reference that shows this.

2023-09-20 08:50 UTC, cpaelzer commented on VersionStrings.md
> +Yes that means, from just the version, you can not differentiate between a _native Debian package that was synced_ and a _native package in Ubuntu_
already spotted and fixed

2023-09-20 08:50 UTC, cpaelzer commented on VersionStrings.md
> +until the [Debian import freeze](https://wiki.ubuntu.com/DebianImportFreeze) date is met, then this is deactivated to stabilize the upcoming Ubuntu release.
correct

2023-09-20 08:51 UTC, cpaelzer commented on VersionStrings.md
> +So what if one needs to rebuild a package, for example due to a libarary transition to build against new versions of other packages,
thanks

2023-09-20 08:53 UTC, cpaelzer commented on VersionStrings.md
> +As outlined there _" will be automatically imported from Debian where they have not been customized for Ubuntu, that is when the version number of the
In the links above - clarified and improved the following sentence

2023-09-20 08:54 UTC, cpaelzer commented on VersionStrings.md
> +* If there is already a `ubuntuX` suffix there would be no auto-sync anyway, so increment the existing suffix
ack

2023-09-20 08:55 UTC, cpaelzer commented on VersionStrings.md
> +but in this situation auto-syncing isn't active anyway and the need for upgradability apply.
ack

2023-09-20 08:55 UTC, cpaelzer commented on VersionStrings.md
> +There are more special cases, especially related to backports (As in backports of new versions via SRU, not as in https://wiki.ubuntu.com/UbuntuBackports).
already spotted and fixed

2023-09-20 08:55 UTC, cpaelzer commented on VersionStrings.md
> +* Add an increment that can be used in subsequent individual per release SRU uploads like `.1`
ack

2023-09-20 08:56 UTC, cpaelzer commented on VersionStrings.md
> +(see the section _Adding a change in Ubuntu as a stable release update_ above)
ack

2023-09-20 08:56 UTC, cpaelzer commented on VersionStrings.md
> +it will lose all its former version suffix. This is a common practice on some
ack

2023-09-20 08:57 UTC, cpaelzer commented on VersionStrings.md
> +> Example: _Uploading `3.1` but packaging wise using what is already in LTS and LTS+1, not with all the Ubuntu changes that might be in `3.1-1ubuntu2`_
ack

2023-09-20 08:57 UTC, cpaelzer commented on VersionStrings.md
> +The new version is independent to the former version of the target release, here an example for 22.04:
ack

2023-09-20 08:59 UTC, cpaelzer commented on VersionStrings.md
> +* Add an increment that can be used in subsequent individual per release SRU uploads like `.1`
ack

2023-09-20 08:59 UTC, cpaelzer commented on VersionStrings.md
> +The new version is again independent to the former version that was present in the target release.
ack

2023-09-20 10:05 UTC, cpaelzer commented on VersionStrings.md
> +> Example: _Uploading `3.1` to LTS and LTS+1 being more or less identical to what is in -devel in `3.1`_
ack

2023-09-20 10:06 UTC, cpaelzer commented on VersionStrings.md
> +> Example: _Uploading `3.1` caused a regression, so rolling back to the previous version_
ack

2023-09-20 10:06 UTC, cpaelzer commented on VersionStrings.md
> +> Example: _Uploading `3.1` to LTS and LTS+1 being more or less identical to what is in -devel in `3.1-1ubuntu2`_
ack

2023-09-20 10:21 UTC, cpaelzer commented on VersionStrings.md
> +Compare these examples with the _Adding a change in the current Ubuntu development release_ section above.
We can, but we should do this everywhere when I refer to any other sections.

.... 5 of them ... Done

2023-09-20 10:45 UTC, cpaelzer commented
Thanks @s-makin and @panlinux - I think I've included all the great feedback.

@s-makin could you give it a light re-read and tell me if you are now ok with the flow?

@panlinux the only thing left open is the native package question, we could do a poll in the team standup today and see what the consensus is there - WDYT?

2023-09-20 12:10 UTC, s-makin commented on CommittingChanges.md
> +Please see [Version string Format](VersionStrings.md) for details.
```suggestion
Please see [Version string format](VersionStrings.md) for details.
```

2023-09-20 12:12 UTC, s-makin commented on VersionStrings.md
> +The following paragraphs first links to the required basics, which are shared with Debian.
```suggestion
The following paragraphs first link to the required basics, which are shared with Debian.
```

2023-09-20 12:18 UTC, s-makin commented on VersionStrings.md
> +Finally if formerly there has been one or many _no change rebuilds_ there might be a `buildX` suffix which is in this case replaced by `ubuntu1`.
```suggestion
Finally if there has already been one (or many) _no change rebuilds_ there might be a `buildX` suffix which is in this case replaced by `ubuntu1`.
```

2023-09-20 12:20 UTC, s-makin commented on VersionStrings.md
> +List of this and further related Examples:
```suggestion
List of this and further related examples:
```

2023-09-20 12:22 UTC, s-makin commented on VersionStrings.md
> +* Represent that there are Ubuntu changes via `ubuntu1` which also serves as a place increment for further uploads to the development release
```suggestion
* Represent that there are Ubuntu changes via `ubuntu1` which also serves as a place increment for further uploads to the development release.
```

2023-09-20 12:22 UTC, s-makin commented on VersionStrings.md
> +List of this and further related Examples:
```suggestion
List of this and further related examples:
```

2023-09-20 12:24 UTC, s-makin commented on VersionStrings.md
> +List of these and further related Examples:
```suggestion
List of these and further related examples:
```

2023-09-20 12:31 UTC, s-makin commented on VersionStrings.md
> +Furthermore native packages versioning is package dependent, if it uses only _major_ or a _major.minor_ or any other version pattern is the maintainers choice.
```suggestion
Furthermore, native package versioning is package dependent; whether it uses only _major_, or _major.minor_, or any other version pattern is the maintainer's choice.
```

2023-09-20 12:31 UTC, s-makin commented on VersionStrings.md
> +Due to that selecting the right subsequent version requires to check the package history or confer with its maintainer.
```suggestion
Due to that, selecting the right subsequent version requires you to check the package history or confer with its maintainer.
```

2023-09-20 12:31 UTC, s-makin commented on VersionStrings.md
> +List of these and further related Examples:
```suggestion
List of these and further related examples:
```

2023-09-20 12:33 UTC, s-makin commented on VersionStrings.md
> +And as we learned in _[Adding a change in the current Ubuntu development release](VersionStrings.md#version-adding-a-change-in-the-current-ubuntu-development-release)_
```suggestion
And as we learned in _[adding a change in the current Ubuntu development release](VersionStrings.md#version-adding-a-change-in-the-current-ubuntu-development-release)_
```

2023-09-20 12:41 UTC, s-makin commented on VersionStrings.md
> +above adding a change in Ubuntu will add a `ubuntuX` suffix, which thereby prevents that automatic sync process from clobbering these changes.
"clobbering" gave me a bit of a pause there because it's quite a UK-specific slang - I'm not sure what you mean by it, but it might be not what I think it means so I just want to clarify that I've understood it correctly. When we say something gets clobbered, it usually means beaten with a blunt object. My inference then is that the automatic sync process has the capacity to "mess up" the changes. If I've understood this correctly, I'd suggest changing clobbering to something like "interfering with" to avoid the slang.

2023-09-20 12:42 UTC, s-makin commented on VersionStrings.md
> +* If there is already an `ubuntuX` suffix there would be no auto-sync anyway, so increment the existing suffix
```suggestion
* If there is already an `ubuntuX` suffix there would be no auto-sync anyway, so increment the existing suffix.
```

2023-09-20 12:43 UTC, s-makin commented on VersionStrings.md
> +List of this and further related Examples:
```suggestion
List of this and further related examples:
```

2023-09-20 12:43 UTC, s-makin commented on VersionStrings.md
> +(see the section _(Adding a change in Ubuntu as a stable release update)[VersionStrings.md#version-adding-a-change-in-ubuntu-as-a-stable-release-update]_ above).
```suggestion
(see the section _(adding a change in Ubuntu as a stable release update)[VersionStrings.md#version-adding-a-change-in-ubuntu-as-a-stable-release-update]_ above).
```

2023-09-20 12:44 UTC, s-makin commented on VersionStrings.md
> +* Signal that it was not yet packaged before in this Ubuntu release before via `ubuntu0.`
```suggestion
* Signal that it was not yet packaged before in this Ubuntu release before via `ubuntu0.`.
```

2023-09-20 12:44 UTC, s-makin commented on VersionStrings.md
> +List of this and further related Examples:
```suggestion
List of this and further related examples:
```

2023-09-20 12:45 UTC, s-makin commented on VersionStrings.md
> +The new version is independent of the former version of the target release, here an list of examples targetting 22.04:
```suggestion
The new version is independent of the former version of the target release. Here is a list of examples targeting 22.04:
```

2023-09-20 12:45 UTC, s-makin commented on VersionStrings.md
> +List of this and further related Examples:
```suggestion
List of this and further related examples:
```

2023-09-20 12:46 UTC, s-makin commented on VersionStrings.md
> +The new version is again independent of the former version that was present in the target release, here examples targetting 22.04.
```suggestion
The new version is again independent of the former version that was present in the target release, here examples targeting 22.04:
```

2023-09-20 12:46 UTC, s-makin commented on VersionStrings.md
> +List of this and further related Examples:
```suggestion
List of this and further related examples:
```

2023-09-20 12:47 UTC, s-makin commented on VersionStrings.md
> +List of this and further related Examples:
```suggestion
List of this and further related examples:
```

2023-09-20 12:49 UTC, panlinux commented
> @panlinux the only thing left open is the native package question, we could do a poll in the team standup today and see what the consensus is there - WDYT?

Yes please :)

2023-09-20 12:51 UTC, panlinux commented
Mind you github is reporting some conflicts

2023-09-22 06:29 UTC, cpaelzer commented on VersionStrings.md
> +| 2.0 (native in Ubuntu)       | 2.1                           |
There is no point in adding that as it would never be synced from anywhere.
We'd also never add `ubuntuX` either.

I think both work, lets decide this by a social battle (majority wins) and then land this (I'm happy to correct if what is right is formally defined anywhere).

```
$ for p in $(dpkg -l | awk '/^ii/ {pkg=$2; ver=$3; printf("%70s %45s\n", ver, pkg);}' | awk '$1 !~ /-/' | awk '$1 !~ /ubuntu/'  | sort -u -k 1,1 | awk '{print $2}'); do if ! rmadison -u debian $p -a source -s unstable | grep -q source; then echo "$p is native and only in ubuntu"; apt changelog $p > $p.changelog; else echo "$p is native in Debian"; fi; done
...
$ grep -i -B4 'no.*change.*rebuild' *.changelog | grep urgency | grep build -c
11
$ grep -i -B4 'no.*change.*rebuild' *.changelog | grep urgency | grep -v build -c
4
```

This was just my laptop, I didn't bother checking the full archive.

So both exist and work and arrr

You know what, I'll write it as "weakly defined, both are allowed"

2023-09-22 07:21 UTC, cpaelzer commented on CommittingChanges.md
> +### Version string Format
Oh wait - what - also format to lower case.
Arr I have changed all occurrences to just lower the "string".

...

Also doing Format -> format in all places now

2023-09-22 07:22 UTC, cpaelzer commented on CommittingChanges.md
> +Please see [Version string Format](VersionStrings.md) for details.
yep, have this already

2023-09-22 07:24 UTC, cpaelzer commented on README.md
> +   - [Chosing a Version](VersionStrings.md)
Already got this one ...

2023-09-22 07:25 UTC, cpaelzer commented on VersionStrings.md
> +Version string Format
ack

2023-09-22 07:29 UTC, cpaelzer reviewed
Taken in all easy changes as is - thank you so much.
Then looking at what is left open ...

2023-09-22 07:52 UTC, cpaelzer commented on VersionStrings.md
> +above adding a change in Ubuntu will add a `ubuntuX` suffix, which thereby prevents that automatic sync process from clobbering these changes.
No it is not "interfering" which demonstrates it is maybe the wrong word.
"Clobbering changes" is usually referred to describing that changes that were done are entirely lost due to that action.

More like:
State1 => changes => State2 => clobbering changes => State1

And certainly not beaten with a blunt object :-)

I have tried to make it better and now have:

... will add a `ubuntuX` suffix, which prevents the automatic synchronisation process, which thereby will ensure Ubuntu is not unintentionally losing these changes.

2023-09-22 08:06 UTC, cpaelzer commented
Thank you all for your continuous work with me on this. Let us hope it helps many future uploaders to pick the right version with less confusion.

Acks are good, I'll squash logically, rebase and eliminate conflicts and merge ...

2023-09-22 08:29 UTC, merged